### PR TITLE
Update wordpad.py

### PR DESCRIPTION
**Pull request by denfromufa**
fixes https://github.com/pythonnet/pythonnet/issues/183#issuecomment-205009786

### CODE REVIEW

**Comment by denfromufa** [comment]
@stonebig @vmuriart this should fix now wordpad.py demo

**Comment by tonyroberts** [comment]
@denfromufa does this demo work for you? I just tried it with the change from this PR and whenever I try to save or open a file it hangs. I've not looked into why (and I don't know if it ever worked?).

**Comment by tonyroberts** [comment]
Oh ok, I see. It's just because the main thread isn't set up as an STA thread. I'll fix than in another PR.

**Comment by denfromufa** [comment]
@tonyroberts I have the same problem - I never actually tried saving or
opening files before. Looks like it never worked at least since github
transition. I just tried with versions 2.0+. @stonebig did you get save or
open files to work in wordpad.py?

**Comment by tonyroberts** [comment]
@denfromufa @stonebig this is fixed now (see above and PR #198).

**Pull request merged**
