### PR TITLE
Fixed errors breaking .NET Remoting on method invoke (#276)

### PR DESCRIPTION
**Pull request by callumnoble**
### What does this implement/fix? Explain your changes.

#276 

### Checklist

Check all those that are applicable and complete.

-   [ ] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [ ] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [ ] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by denfromufa** [comment]
@jcarole follow instructions in wiki on downloading the wheels from artifacts on Appveyor CI.

**Comment by jcarole** [comment]
@denfromufa The previous link I used, https://ci.appveyor.com/project/pythonnet/pythonnet/build/master-1147, no longer has any files. Did this ever get merged in to main? So would I grab the build that supports 3.7?

**Comment by denfromufa** [comment]
@jcarole, yes this PR is merged into master, see the purple label at the top. The older artifacts get deleted by Appveyor CI automatically.

**Comment by jcarole** [comment]
@denfromufa Thank you! This old github-ignorant coder needs to get past the 80s ; )

**Pull request merged**
