### PR TITLE
Update setup.py - use vswhere for msbuild 15+

### PR DESCRIPTION
**Pull request by denfromufa**
### What does this implement/fix? Explain your changes.

VS 2017 issues with msbuild

### Does this close any currently open issues?

#539 

### Any other comments?

@dmitriyse needs to be added to this commit

### Checklist

Check all those that are applicable and complete.

-   [ ] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [ ] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [ ] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by denfromufa** [comment]
UnmanagedExports complaining about ildasm.exe:

UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error : Microsoft.Build.Utilities.ToolLocationHelper could not find ildasm.exe. 

[.\pythonnet\src\clrmodule\clrmodule.csproj]

**Comment by denfromufa** [comment]
although unmanaged exports complains, the build looks find and the "import clr" works. this issue seems very common:

https://stackoverflow.com/questions/44836800/could-not-find-ildasm-exe
https://stackoverflow.com/questions/39811809/ildasm-for-net-4-5

**Comment by dmitriyse** [comment]
Build fails due to 12.04 upgraded to Mono 5.2 + travis apt command have a bad thing --no-install-suggest.
To overcome this issue you can try this:
```yaml
addons:
  apt:
    sources:
      - sourceline: deb http://download.mono-project.com/repo/ubuntu precise main
        key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA6A19B38D3D831EF
    packages:
      - mono-devel
      - ca-certificates-mono

Probably it's time to merge https://github.com/pythonnet/pythonnet/pull/518 , as it's contain many things like that already debugged.

**Comment by denfromufa** [comment]
closing this in favor #518 assuming @dmitriyse moves vswhere to tools subdirectory

**Comment by dmitriyse** [comment]
My suggestion https://github.com/pythonnet/pythonnet/pull/540#issuecomment-328618782 did not helps. Strange. 
In the https://github.com/pythonnet/pythonnet/pull/518 I forced to switch to 14.04 ubuntu image, due to dotnet core does not supported on the 12.04 Ubuntu.
In 14.04 image this tip is 100% works.

**Comment by SlimeQ** [comment]
On Windows 10, the ildasm.exe error **does**  prevent installation from completing. I'm using the master branch on 6/6/18.

I attempted to upgrade DllExport and configure the app using DllExport.bat (which was suggested somewhere). This results in the following error:

```
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

delegatemanager.cs(204,13): warning CS0162: Unreachable code detected [C:\Users\quincyc\Documents\Github\pythonnet\src\runtime\Python.Runtime.csproj]
pythonexception.cs(67,13): warning CS0162: Unreachable code detected [C:\Users\quincyc\Documents\Github\pythonnet\src\runtime\Python.Runtime.csproj]
pyobject.cs(50,13): warning CS0162: Unreachable code detected [C:\Users\quincyc\Documents\Github\pythonnet\src\runtime\Python.Runtime.csproj]
pyscope.cs(534,13): warning CS0162: Unreachable code detected [C:\Users\quincyc\Documents\Github\pythonnet\src\runtime\Python.Runtime.csproj]
  Python.Runtime -> C:\Users\quincyc\Documents\Github\pythonnet\src\runtime\bin\Python.Runtime.dll
  Python.Test -> C:\Users\quincyc\Documents\Github\pythonnet\src\testing\bin\Python.Test.dll
dynamic.cs(121,28): warning CS0618: 'PythonEngine.RunString(string, IntPtr?, IntPtr?)' is obsolete: 'RunString is deprecated and will be removed. Use Exec/Eval/RunSimpleString instead.' [C:\Users\quincyc\Documents\Github\pythonnet\src\e
mbed_tests\Python.EmbeddingTest.csproj]
  Python.EmbeddingTest -> C:\Users\quincyc\Documents\Github\pythonnet\src\embed_tests\bin\Python.EmbeddingTest.dll
  Console -> C:\Users\quincyc\Documents\Github\pythonnet\src\console\bin\nPython.exe
  clrmodule -> C:\Users\quincyc\Documents\Github\pythonnet\src\clrmodule\bin\clrmodule.dll
C:\Users\quincyc\Documents\Github\pythonnet\packages\DllExport.1.6.0\tools\net.r_eg.DllExport.targets(68,11): error MSB4064: The "VsDevCmd" parameter is not supported by the "DllExportAppDomainIsolatedTask" task. Verify the parameter ex
ists on the task, and it is a settable public instance property. [C:\Users\quincyc\Documents\Github\pythonnet\src\clrmodule\clrmodule.csproj]
C:\Users\quincyc\Documents\Github\pythonnet\packages\DllExport.1.6.0\tools\net.r_eg.DllExport.targets(56,5): error MSB4063: The "DllExportAppDomainIsolatedTask" task could not be initialized with its input parameters.  [C:\Users\quincyc
\Documents\Github\pythonnet\src\clrmodule\clrmodule.csproj]
```

**Pull request closed without merging**
