### PR TITLE
Change as

### PR DESCRIPTION
**Pull request by koubaa**
### What does this implement/fix? Explain your changes.
Improve behavior of PyObject.As<>.  This is needed to make external function codec work:
https://github.com/pythonnet/codecs/pull/1
...

### Does this close any currently open issues?

...

### Any other comments?

...

### Checklist

Check all those that are applicable and complete.

-   [x] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [x] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [x] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by filmor** [comment]
Hmm, I think in general this is fine because we don't lose anything (`As<PyObject>` will still work), but it's nevertheless a silent breaking change. This is possible in the future, but I wouldn't want to do it during a point-release. Can you introduce a preliminary new function for this behaviour?

**Comment by koubaa** [comment]
@filmor I can do that.  I will also create a new issue to address this in a major release.

**Comment by lostmsu** [comment]
@koubaa if this is specifically targeted to conversion to `object`, why does it have to be generic?

**Comment by koubaa** [comment]
> @koubaa if this is specifically targeted to conversion to `object`, why does it have to be generic?

@lostmsu good point.  It would be more clear to just call it AsObject

**Comment by lostmsu** [comment]
@koubaa there is already `AsManagedObject(Type)`. Does it not work for you? It appears to be doing the same when `Type == object`.

**Comment by koubaa** [comment]
@lostmsu didn't know about that.  I don't need this change anymore

**Pull request closed without merging**
