### PR TITLE
Python 3.9

### PR DESCRIPTION
**Pull request by filmor**
### What does this implement/fix? Explain your changes.

Adds Python 3.9 to CI.

### Checklist

Check all those that are applicable and complete.

-   [x] Make sure to include one or more tests for your change
-   [x] If an enhancement PR, please create docs and at best an example
-   [x] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [ ] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by filmor** [comment]
We'll have to wait until 3.9 is available in both Travis and Appveyor.

**Comment by filmor** [comment]
Waiting for
[ ] https://github.com/appveyor/ci/issues/3541
[ ] https://travis-ci.community/t/python-3-9-0-build/10091 (Discussion)

**Comment by domdfcoding** [comment]
Python 3.9 is now available on Travis

**Comment by filmor** [comment]
@lostmsu This is passing tests now, feel free to review. I'll backport this to 2.5.

**Review by lostmsu — APPROVED** [review]
Looks good, but maybe removing underscore from most members of gen_interop is a bit destructive to file's blame.

I'd also squash.

**Comment by filmor** [comment]
I'll clean things up a bit, but if I ever need to debug this again, I want the double-underscores already gone ;)

**Comment by taixes** [comment]
Hi, it seems this branch is already merged to master but here [here](https://pypi.org/project/pythonnet/) it says that pythonnet does not support python 3.9. Does this page have to be updated or there is still a step I'm missing before python 3.9 is supported?

**Comment by filmor** [comment]
Things are complicated, check #1389.

**Pull request merged**
