### PR TITLE
[WIP] PythonHome Path is correctly set

### PR DESCRIPTION
**Pull request by denfromufa**
*Blank Description*

------------------------

Pending for merge:

- [ ] Generalize/Improve Unittests (has to be able to run in Appveyor, Local (travis could wait since embdded tests arent working there)

- [ ] Rebase and fix merge conflicts. (@vmuriart)

### CODE REVIEW

**Comment by filmor** [comment]
What problem does this fix? Is it still valid?

**Comment by denfromufa** [comment]
Here is the original pull request, I think it is valid fix and the leak is unavoidable and non-essential.

https://github.com/pythonnet/pythonnet/pull/186

**Comment by vmuriart** [comment]
@filmor this is probably the issue they were trying to solve

http://stackoverflow.com/questions/5694706/py-initialize-fails-unable-to-load-the-file-system-codec

I'm having that issue right now trying to run python3 locally...

**Comment by denfromufa** [comment]
Exactly!

**Comment by vmuriart** [comment]
@denfromufa are you/have you had that issue before? I normally pawn off all my Python3 testing to appveyor/travis so never really encountered this before

**Comment by denfromufa** [comment]
This is quite common on Linux when 2-3 Python runtimes are in the path.

**Comment by vmuriart** [comment]
@denfromufa @filmor Anything missing or needed to close/merge this `pr`? I'll do the rebase and fix the merge conflicts if we are good to merge this in.

**Comment by denfromufa** [comment]
The unit definitely needs to be improved

**Comment by vmuriart** [comment]
yup I can see that now. Going to be tricky figuring out how to generalize that one so that it works on `Appveyor` (could use enviroment variables) & Local.

hm... that reminds me, where in the code do we search for the python dll's? I couldn't find it when I posted that `SO` question a few comments back. I couldn't get Python3 to run embedded test no matter way environment variable i update.

**Comment by denfromufa** [comment]
@vmuriart you mean that Python 3 embedded tests are not working when you have multiple Python runtimes installed on your Windows machine?

**Comment by denfromufa** [comment]
Is nPython working?

**Comment by vmuriart** [comment]
That was actually the first time I used `nPython`and it didn't work either. The embedded tests weren't working on `python36` when `python27` was my default python (and original) python install. I updated all references to python27 in my enviroment varialbles and added new ones but nothing worked.

I got it working finally by uninstalling Anaconda Python2.7 and deleting all my python installations. I reinstalled Anaconda Python, but 3.6 this time around as the default. I reinstalled all my python interpreters (including 27) and everything is working now. 

I can test on Python 3.6 by default with no issues, and I can test Python 2.7 after updating `PATH`. I have no idea why it didn't work the other way around though.

**Pull request closed without merging**
