### PR TITLE
Add traceback information to exception

### PR DESCRIPTION
**Pull request by testrunner123**
### What does this implement/fix? Explain your changes.

Attach traceback information to newly created exception.

### Does this close any currently open issues?

#542

### Checklist

Check all those that are applicable and complete.

-   [x] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [x] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [x] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by testrunner123** [comment]
Tested with Python 3.5 64-bit on Windows 7 Pro.

**Comment by denfromufa** [comment]
@testrunner123 there is one conflict in changelog.md and also no testing included.

**Comment by testrunner123** [comment]
@ denfromufa

I added line to CHANGELOG.md, but I can|t understand where conflict is. It was shown that merge automatically is possible.

**Comment by testrunner123** [comment]
I have no write-access to pythonnet:master.

**Comment by testrunner123** [comment]
Travis build is broken because it failed to install mono 4.x packages.

**Comment by denfromufa** [comment]
@testrunner123 those Mono + Travis CI issues have been fixed in @dmitriyse pull requests, which you can cherry pick into your commit.

**Comment by testrunner123** [comment]
> those Mono + Travis CI issues have been fixed in @dmitriyse pull requests, which you can cherry pick into your commit.

The problem is if I try to make a pull request to my branch or master then I am unable to do it. It says: everything is update. I am using web interface.

**Comment by denfromufa** [comment]
@testrunner123 you can only reliably cherry pick from git user interface, e.g. I use sourcetree and @vmuriart uses gitextensions:

https://github.com/gitextensions/gitextensions

Don't try to do it from command-line :)

Only web interface in gitlab supports cherry picking, GitHub and BitBucket do not support this.

**Comment by denfromufa** [comment]
@testrunner123 this should now pass the CI

**Comment by testrunner123** [comment]
THX

**Comment by filmor** [comment]
This isn't quite right (it wasn't before, so you didn't introduce it but you can fix it :)). The documentation of [PyErr_Restore](https://docs.python.org/3.5/c-api/exceptions.html#c.PyErr_Restore) states that you are giving up the references that you pass on, however, the `PythonException` object that the references stem from are `Decref`d on `Dispose`. Best is probably to mark the `PythonException` instance as already disposed in this case.

**Comment by testrunner123** [comment]
I guess you propose to call pe.PythonException.Restore() instead of Runtime.PyErr_Restore(). But this will also take GIL lock, that is already taken at this time ?

I just do not have enough knowledge about python interpreter to make a change and test it...
So may be you can do it right ? :)

**Comment by denfromufa** [comment]
@filmor can you clarify your suggestion a little bit more for @testrunner123 and for me?

**Comment by denfromufa** [comment]
@filmor i suggest to merge this PR and open a separate issue for your suggestion?

**Comment by filmor** [comment]
This PR decrefs an object that we hand over to another function, I don't think it's a good idea to merge it like this. I'll see whether I can do the needed changes.

**Comment by filmor** [comment]
So, from a review point of view, this is fine by me, we just need to fix the whole refcount situation, introducing another Incref before calling restore should be enough.

**Comment by denfromufa** [comment]
@filmor  what is going on today :)

**Pull request merged**
