### PR TITLE
include fake c libs for pycparser to work

### PR DESCRIPTION
**Pull request by denfromufa**
https://github.com/pythonnet/pythonnet/issues/336

### CODE REVIEW

**Comment by vmuriart** [comment]
It creates merge conflict with #337, but I'll rebase #377 after this is merged.

**Comment by denfromufa** [comment]
@vmuriart let me include 2.2.2 tag in setup.py and __version__ in this pull request?

**Comment by vmuriart** [comment]
Not necessary, I'll add them when updating the changelog. Otherwise its going to trigger two more builds on `AppVeyor` which takes along time...

**Comment by vmuriart** [comment]
Actually, if you can take a look at #335 while we wait for these to finish that would be great.
It will make getting the final built whl from appveyor that much faster.

**Comment by denfromufa** [comment]
@vmuriart ok, then please add release tag, update changelog, release notes, setup.py, and `__version__` after this is merged.

**Pull request merged**
