### PR TITLE
[WIP] handling ByRef arguments for method overloading - update methodbinder.cs

### PR DESCRIPTION
**Pull request by denfromufa**
byref handling:

https://github.com/pythonnet/pythonnet/issues/226

### CODE REVIEW

**Comment by denfromufa** [comment]
TODO: take care of out parameters also

**Comment by denfromufa** [comment]
grab the wheels from this place (navigate to specific python version and then artifacts tab): 

https://ci.appveyor.com/project/denfromufa/pythonnet/build/1.0.78

**Comment by stonebig** [comment]
will there be a maintenance release soon ?

**Comment by denfromufa** [comment]
@stonebig I just asked @tonyroberts what are the plans with pull requests and have not received any reply yet.

in the meantime I mirrored pythonnet on bitbucket in case I have to fix the CI and merge pull requests faster:

https://bitbucket.org/pythonnet/pythonnet

**Comment by tonyroberts** [comment]
Any plans for any tests for this PR? The title is still WIP but am I to take it that it no longer is from your comments?

**Comment by tonyroberts** [comment]
@denfromufa Expecting a reply immediately from someone in a different time zone is unreasonable. If you want PRs to be merged in a timely fashion please ensure they include any relevant tests and are clearly explained. Labeling one as work in progress and then using it for a long discussion thread involving TODOs doesn't make it easy to determine when the right time to merge it is.

@stonebig happy to do a maintenance release once these fixes are in. Looks like there are some problems currently on the mono side though, so those might have to be addressed first.

**Comment by denfromufa** [comment]
My comments were in general for all PRs. There were some requests before
from other users that were not replied. I can send you the link(s) if you
think that you missed them.

I'm going to add tests to this pull request.

**Comment by tonyroberts** [comment]
@denfromufa in order to close the PRs this morning I had to go through cherry-picking various commits out of them, amending changes because of improper formatting, and subsequently fixing bugs introduced  due to a lack proper care and attention when submitting the PRs. Most of these had comments on them indicating that there were problems with them. In other open source projects, they would simply have been rejected but I took the time to fix them up and get them into the project.

In the future, if you want PRs to be merged more quickly you may take it upon yourself to clean them up (code formatting, merge-commits that shouldn't be there etc.). If the merge is trivial and there is a decent explanation of what it is, and the code looks clean (and tested) I have no issue merging them immediately. If I have to spend time going through them and fixing them up then they will sit there until either they get closed or I have time to do it myself.

**Comment by denfromufa** [comment]
@tonyroberts thanks for doing this tedious work with cherry-picking! Does this preserve the authors in the commits, i.e. will the authors of these original commits be listed in contributors to pythonnet?

https://github.com/pythonnet/pythonnet/graphs/contributors

**Comment by tonyroberts** [comment]
Yes

**Comment by filmor** [comment]
@denfromufa Is this one still relevant?

**Pull request closed without merging**
