### PR TITLE
Disable 3.8 tests in AppVeyor, as they never pass yet anyway

### PR DESCRIPTION
**Pull request by lostmsu**
Subj

### CODE REVIEW

**Comment by filmor** [comment]
What for? As they are allowed failures, we can just keep them until we have actually fixed the tests.

**Comment by lostmsu** [comment]
@filmor they take extra ~20 minutes to run.

**Comment by filmor** [comment]
Hmm

**Comment by lostmsu** [comment]
I am reopening this, as it also affects attempts to rerun CI where a single leg randomly failed, as it always reruns all 3.8 in addition to that, turning a 5 min job into 25 min job.

**Comment by filmor** [comment]
Okay, let's do this for now. Linking #1066 for reference.

**Pull request merged**
