### PR TITLE
Fix incorrect string marshalling in PyScope.Exec

### PR DESCRIPTION
**Pull request by NickSavin**
### What does this implement/fix? Explain your changes.

Fixed incorrect string Marshaling in PyScope.Exec method

### Does this close any currently open issues?
fixed issue https://github.com/pythonnet/pythonnet/issues/818

### CODE REVIEW

**Comment by filmor** [comment]
@lostmsu Do you think it would be okay to merge this with a `#if !PYTHON2` check for the "new" code before 2.5? That already catches most interesting cases without breaking anything (valid) that used to work.

**Comment by lostmsu** [comment]
@filmor yep, that sounds good.

**Comment by lostmsu** [comment]
@filmor although, it would be good to have a test for this fix too.

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/pythonnet/pythonnet?pullRequest=824) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/pythonnet/pythonnet?pullRequest=824) before we can accept your contribution.<br/><br/>:x: NickSavin [sign now](https://cla.dotnetfoundation.org/pythonnet/pythonnet?pullRequest=824)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/pythonnet/pythonnet?pullRequest=824) it.</sub>

**Comment by filmor** [comment]
Github got confused here, I merged the commit manually now. Thank you for your contribution :)

**Pull request closed without merging**
