### PR TITLE
Try to detect whether the clr module is partially initialised

### PR DESCRIPTION
**Pull request by filmor**
This should fix issue #1582. While the respective behaviour (setting the member value `_initializing`) is not documented, it has been that way since at least 3.4. As we control `clr`, it can also not happen, that the value is accidentally set.

### What does this implement/fix? Explain your changes.

...

### Does this close any currently open issues?

...

### Any other comments?

...

### Checklist

Check all those that are applicable and complete.

-   [ ] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [ ] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [ ] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by lostmsu** [comment]
Do you know how to reproduce the original issue? Can you confirm you tried with and without the fix, and it at least seems not to repro with the fix?

**Comment by filmor** [comment]
Nope. I just read the Python source code, and it's clear how exactly this can happen. There is however no public interface to check for this situation, so apart from this hacky version, we are out of luck anyhow.

**Comment by lostmsu** [comment]
I don't see any code that would set that `_initializing` property. Is it set implicitly somehow?

**Comment by filmor** [comment]
These are the relevant parts of CPython:

https://github.com/python/cpython/blob/f4c03484da59049eb62a9bf7777b963e2267d187/Lib/importlib/_bootstrap.py#L678-L707

https://github.com/python/cpython/blob/f4c03484da59049eb62a9bf7777b963e2267d187/Objects/moduleobject.c#L722-L741

The latter is exactly the part that's `False` in the error case that you have observed.

**Comment by lostmsu** [comment]
@filmor do you have a good theory why this could happen during shutdown then? The original bug speaks about shutdown scenario.

**Comment by filmor** [comment]
It must be that the module is gone and some code (the loader?) tries to reinitialise it, races with the initialisation and hits this bump.

**Comment by filmor** [comment]
@lostmsu What do you think about this PR?

**Comment by lostmsu** [comment]
@filmor I am not convinced unless we have a repro.

**Pull request closed without merging**
