### PR TITLE
Msbuild15 patch

### PR DESCRIPTION
**Pull request by christopherpow**
### What does this implement/fix? Explain your changes.

https://github.com/pythonnet/pythonnet/issues/434

### Does this close any currently open issues?

https://github.com/pythonnet/pythonnet/issues/434

### Any other comments?

https://github.com/pythonnet/pythonnet/issues/434

### Checklist

Check all those that are applicable and complete.

-   [ ] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [X] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [X] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by denfromufa** [comment]
@filmor @vmuriart can you guys approve this? we need at least 2 approvals

**Comment by vmuriart** [comment]
Why was the `bld.bat` updated? It isn't necessary for this `pr`.

**Comment by denfromufa** [comment]
what if the local conda build is required with vs 2017?

**Comment by vmuriart** [comment]
Same could be said for `vs2015` or any other version. Since `setup.py` does the job of figuring out where msbuild is located the `bld.bat` file probably isn't needed.

**Comment by denfromufa** [comment]
@vmuriart so maybe then we can remove bld.bat in another cleanup PR?

**Comment by denfromufa** [comment]
@vmuriart anyway feel free to merge this with whatever you decide on msbuild in bld.bat.

**Comment by vmuriart** [comment]
Just did. thanks for the `pr` @christopherpow 

@denfromufa is there a way to exclude to `AUTHORS.md` from mention-bot?

**Pull request merged**
