### PR TITLE
Update moduleobject.cs

### PR DESCRIPTION
**Pull request by icetiger1974**
I am a novice in English and pythonnet.
But I am a Fan of pythonnet.

The Proposed file is about NTFS Security.
https://stackoverflow.com/questions/4496697/what-is-zone-identifier

please check~

### What does this implement/fix? Explain your changes.

... In case of Windows 10, We can find the DLL with Blocking. 
.. But current code provides wrong information. So I modified these code  lines

### Does this close any currently open issues?

... I can not find open issues

### Any other comments?

... none

### Checklist

Check all those that are applicable and complete.

-   [ ] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [ ] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [ ] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by denfromufa** [comment]
@icetiger1974 this seems legitimate, what kind of error does pythonnet show without this fix for these "unsecure" dlls?

**Comment by denfromufa** [comment]
@icetiger1974 appveyor tests failing, weird.

**Comment by denfromufa** [comment]
@icetiger1974 merged, thanks!

**Comment by icetiger1974** [comment]
Hi denfromufa
Thank you very much.
Best regards
icetiger1974

**Pull request merged**
