### PR TITLE
stackoverflow/slack shields

### PR DESCRIPTION
**Pull request by denfromufa**

### CODE REVIEW

**Comment by vmuriart** [comment]
That is one long shield, and the `label` doesn't work because of the period in `python.net`.
`https://img.shields.io/stackexchange/stackoverflow/t/python.net.svg?label=StackOverflow`

We can use `https://img.shields.io/badge/StackOverflow-python.net-blue.svg` instead though. The original badge kept timing out on me. What do you think?

**Comment by vmuriart** [comment]
Might as well add the `slack` badge too. We can use either `https://img.shields.io/badge/chat-slack-color.svg?style=social?link=http://left&link=http://right`  or make another generic one.

**Comment by denfromufa** [comment]
it works on my machine:

https://github.com/pythonnet/pythonnet/blob/ef6e47d0ee5d5b02e6c50f81d86567cc10c126b8/README.md

**Comment by vmuriart** [comment]
It works on mine about 25% of the time.

**Comment by vmuriart** [comment]
Here's the complete slack badge `https://img.shields.io/badge/chat-slack-color.svg?style=social&link=https://pythonnet.slack.com&link=https://pythonnet.slack.com` You don't need to add an extra link ontop of it.

**Comment by vmuriart** [comment]
Can you match the badge link style that the other badges are using? The image link is located at the bottom of the `README.md`

**Pull request merged**
