### PR TITLE
QuantConnect Update

### PR DESCRIPTION
**Pull request by C-SELLERS**
### What does this implement/fix? Explain your changes.

This PR seeks to bring QuantConnect/PythonNet 's changes to the root repo.

Since QuantConnect's fork was so distant from the root repo it required that I reapply all the needed changes in order to keep desired functionality. To denote this in the commits I referenced the PR I was trying to replicate. Please be aware that Github will link these to the root #n PR but they are all referencing QuantConnect/PythonNet PRs

### Any other comments?

QuantConnect Changes Reflected (Reference QuantConnect/PythonNet for original PR):

- Support decimal, timespan, datetime, implicit, and nullable conversions (QuantConnect/pythonnet#1, QuantConnect/pythonnet#8, QuantConnect/pythonnet#10, QuantConnect/pythonnet#14, QuantConnect/pythonnet#15, QuantConnect/pythonnet#25)
- Use Float in Python for Decimal conversion (Performance improvement QuantConnect/pythonnet#19)
- Some logging on boot up (QuantConnect/pythonnet#34)
- Support List conversion (QuantConnect/pythonnet#37)
- AssemblyManager Cache (Performance improvement QuantConnect/pythonnet#38)
- Generic Util race condition fix (QuantConnect/pythonnet#38)
- Support KeyValuePairEnumerable Objects (QuantConnect/pythonnet#42)

Patches to address failures in Lean:
- MethodBinder changes to allow implicit conversion. This one was particularly tricky and seemed impossible to patch together with the MethodBinder.cs in the root. Unfortunately it involved tearing apart a lot of it and rebuilding only what was needed. It may be possible to refactor this to look more like the root and still pass our tests.  ( 58d5df0 ,  44e089a , 108eacf , 6379568 , 9f2796a ) 
- Revert PythonNet PR #1240 ; this PR broke fetching interface derived classes data members that weren't defined in the interface.   ( ed6ab18 )
- Converting PyObject to Int fix; this reflects the way PythonNet used to convert values to Int32, 64, unsigned etc, with `PyNumber_Long` but still keeps the use of `Runtime.PyLong_AsSignedSize_t` to finish the conversion. The bug that discovered this was trying to convert a Python float to int, this used to work but was failing until this refactor. Reference the added test in bd94e49. ( d87584b )

Tests added:
- TimeDelta and DateTime Conversion Tests ( 508db2e )
- List Conversion tests ( 5839d21 )
- Dictionary Tests ( 101624e )
- MethodBinder Tests ( bf1755d )
- OperatorInequality Test ( b0aca5c )
- PrimitiveIntConversion Test ( bd94e49 )
- Interface Classes Test ( cd06d10 )

Some tests had to be adjusted for behavior changes caused by our commits. I have adjusted enough to have all PythonNet embedded tests passing, but there are still some issues with PyTests that need to be addressed/resolved. 

I'm aware this a _huge collection_ of changes, so I don't expect this to be easy but would hope maybe there is a way to bring our branches together so we can help improve PythonNet in the future.

Also note this branch is also a pending PR to QuantConnect/PythonNet . Reference this PR at https://github.com/QuantConnect/pythonnet/pull/47

### Checklist

Check all those that are applicable and complete.

-   [x] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [x] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [ ] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/pythonnet/pythonnet?pullRequest=1385) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/pythonnet/pythonnet?pullRequest=1385) before we can accept your contribution.<br/><br/>:x: C-SELLERS [sign now](https://cla.dotnetfoundation.org/pythonnet/pythonnet?pullRequest=1385)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/pythonnet/pythonnet?pullRequest=1385) it.</sub>

**Comment by filmor** [comment]
Thank you for taking this up again.

>     * Support decimal, timespan, datetime, implicit, and nullable conversions ([QuantConnect#1](https://github.com/QuantConnect/pythonnet/pull/1), [QuantConnect#8](https://github.com/QuantConnect/pythonnet/pull/8), [QuantConnect#10](https://github.com/QuantConnect/pythonnet/pull/10), [QuantConnect#14](https://github.com/QuantConnect/pythonnet/pull/14), [QuantConnect#15](https://github.com/QuantConnect/pythonnet/pull/15), [QuantConnect#25](https://github.com/QuantConnect/pythonnet/pull/25))
> 
>     * Use Float in Python for Decimal conversion (Performance improvement [QuantConnect#19](https://github.com/QuantConnect/pythonnet/pull/19))
I'm still very much against doing these conversions without a way to shut them off (while I agree that they might be good defaults). We nowadays have a system to implement additional conversions and configure them at runtime, codecs for the types you listed would be appreciated: https://github.com/pythonnet/pythonnet/wiki/Codecs:-customizing-object-marshalling-between-.NET-and-Python

>     * Some logging on boot up ([QuantConnect#34](https://github.com/QuantConnect/pythonnet/pull/34))
Straight `Console.Write`s will not get accepted. Trace logging might be, as long as it doesn't pull in additional dependencies (e.g. https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.trace?view=net-5.0)

>     * Support List conversion ([QuantConnect#37](https://github.com/QuantConnect/pythonnet/pull/37))
This might also be implementable as a codec. I'll have a closer look

>     * AssemblyManager Cache (Performance improvement [QuantConnect#38](https://github.com/QuantConnect/pythonnet/pull/38))
This looks nice, needs a separate PR.

>     * Generic Util race condition fix ([QuantConnect#38](https://github.com/QuantConnect/pythonnet/pull/38))
Is this still applicable?

>     * Support KeyValuePairEnumerable Objects ([QuantConnect#42](https://github.com/QuantConnect/pythonnet/pull/42))
Also looks like a codec candidate.

>     * MethodBinder changes to allow implicit conversion. This one was particularly tricky and seemed impossible to patch together with the MethodBinder.cs in the root. Unfortunately it involved tearing apart a lot of it and rebuilding only what was needed. It may be possible to refactor this to look more like the root and still pass our tests.  ( [58d5df0](https://github.com/pythonnet/pythonnet/commit/58d5df0fe731e3fe27f71316869ef5aad932e96f) ,  [44e089a](https://github.com/pythonnet/pythonnet/commit/44e089ad612100da4f40a90ab73f9b19c9cb4512) , [108eacf](https://github.com/pythonnet/pythonnet/commit/108eacfd0ab5535ba8bf4333f51dfec838c87b3d) , [6379568](https://github.com/pythonnet/pythonnet/commit/63795684e281f1cf82e79d1587e4bd675f90f4d8) , [9f2796a](https://github.com/pythonnet/pythonnet/commit/9f2796a7b6aa83eaa4e958b1aaab25efe59b7f43) )
This would definitely need a separate PR. You could start with a PR that adds the tests.

>     * Revert PythonNet PR #1240 ; this PR broke fetching interface derived classes data members that weren't defined in the interface.   ( [ed6ab18](https://github.com/pythonnet/pythonnet/commit/ed6ab18ca04337db37f61ba8efaf910b01a468f1) )
Could you give a concrete example of what is failing now? Can it be mitigated using the `__implementation__` member?

>     * Converting PyObject to Int fix; this reflects the way PythonNet used to convert values to Int32, 64, unsigned etc, with `PyNumber_Long` but still keeps the use of `Runtime.PyLong_AsSignedSize_t` to finish the conversion. The bug that discovered this was trying to convert a Python float to int, this used to work but was failing until this refactor. Reference the added test in [bd94e49](https://github.com/pythonnet/pythonnet/commit/bd94e4918b95815aea9bdcb1f19918b125279b14). ( [d87584b](https://github.com/pythonnet/pythonnet/commit/d87584bad151fc38aa7d904bf6c4cf7bd80a1760) )
This looks good, can you create a PR for this one?

**Comment by koubaa** [comment]
@filmor @C-SELLERS I sent an email to the pythonnet group about issues coming from #1240.  @lostmsu suggested some things (here are 4 and 5 of his suggestions):

"
4. IronPython apparently allows explicit interface implementations to be called (instead of returning interface-wrapped instances), if there’s no conflict with regular methods. Perhaps we should consider this as an option.
5. Alternatively, we can keep wrapped instances, but allow to resolve public members too if the method is not found in the interface. I like this option better than 4, because actual type of an element in ISomething[] won’t change behavior of invoking interface member. It might still affect `hasattr`, but this is somewhat expected."

I think (4) is something like a revert.

**Comment by lostmsu** [comment]
>> Converting PyObject to Int fix; this reflects the way PythonNet used to convert values to Int32, 64, unsigned etc, with PyNumber_Long but still keeps the use of Runtime.PyLong_AsSignedSize_t to finish the conversion. The bug that discovered this was trying to convert a Python float to int, this used to work but was failing until this refactor. Reference the added test in bd94e49. ( d87584b )

> This looks good, can you create a PR for this one?

The old behavior (implicit conversions between numerical types like in the new test) should not be restored.

**Comment by lostmsu** [comment]
> I'm still very much against doing these conversions without a way to shut them off (while I agree that they might be good defaults). We nowadays have a system to implement additional conversions and configure them at runtime, codecs for the types you listed would be appreciated: https://github.com/pythonnet/pythonnet/wiki/Codecs:-customizing-object-marshalling-between-.NET-and-Python

We also have a repository for community-contributed codecs: https://github.com/pythonnet/codecs

**Comment by C-SELLERS** [comment]
Thank you guys for your feedback!

I plan to look into these when permitted and hope to start PR'ing the changes individually that can work! I definitely need to take some time and look at the codec setup you guys have, I wasn't quite sure how it worked and I didn't really understand the wiki either. I'll search for some examples and test it out and see if our conversions can be done that way.

**Pull request closed without merging**
