### PR TITLE
Update unmanaged exports

### PR DESCRIPTION
**Pull request by denfromufa**
https://github.com/pythonnet/pythonnet/issues/95

### CODE REVIEW

**Comment by tonyroberts** [comment]
I had to fix the project file for this as well - it's not enough to just update packages.config. Please test your changes before creating pull requests and then pestering me to merge them.

**Comment by denfromufa** [comment]
Well, I tested locally and did not notice until later time, but had no
opportunity to correct this pull request at that time.
Can you show any comment where I asked to merge my unfinished pull
request(s)?
Sorry for pestering you, but other people were waiting for some fixes in
master and last time you replied was about 2 months ago.

**Comment by tonyroberts** [comment]
Pull requests are a request for code to be pulled (hence the name). There is no need to comment requesting that the code be pulled, as that's the purpose of a pull request! Code that is not ready to be pulled should be worked on in your own fork, preferably in a topic branch if it's anything other than a simple change.

**Comment by matthid** [comment]
@tonyroberts people often use PRs to check the state of CI (I do occasionally as well) without the need to test on a linux system for example. They are often marked as WIP and give you the opportunity to comment / discuss early on.

**Comment by tonyroberts** [comment]
Sure, I've no problem with that if clearly marked. I don't think that was the case here though, it was just something that didn't get picked up because the appveyor build didn't run. Personally, I have my own CI jobs set up against my own fork, but that's just my preference.

**Pull request merged**
