### PR TITLE
Added CoreCLR 2.0 build target. Compile issues fixed.

### PR DESCRIPTION
**Pull request by dmitriyse**
### What does this implement/fix? Explain your changes.
Added dotnet core 2.0 build target. All tests are passed under win, py35, x64.
...

### Does this close any currently open issues?
Work towards https://github.com/pythonnet/pythonnet/issues/96
...

### Any other comments?
After a half of a year CoreCLR 1.0 will go away, so we can only offer CoreCLR 2.0 support. 

Porting to CoreCLR 2.0 is much simpler than to CoreCLR 1.0. So we can do all the work right in the master. Xplat build fortunately can coexist side-by-side with the current build.
(See https://github.com/pythonnet/pythonnet/pull/518)

...

### Checklist

Check all those that are applicable and complete.

-   [ ] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [ ] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [ ] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by dmitriyse** [comment]
Tested under windows, miniconda python 3.5, x64. All tests are passed.

**Comment by denfromufa** [comment]
@dmitriyse why do you have 2 similar pull requests?

**Comment by dmitriyse** [comment]
This https://github.com/pythonnet/pythonnet/pull/518 PR contains only new build system which is able to build all current targets for windows and linux. And contains absolutely minimum changes in the code.

But this request contains NetStandard 2.0 build target + fixes in code to allow compile and pass tests.

**Comment by dmitriyse** [comment]
Please see this comment https://github.com/pythonnet/pythonnet/pull/518#issuecomment-318996219, this PR should add new build target after https://github.com/pythonnet/pythonnet/pull/518 will be merged into the master.

**Comment by denfromufa** [comment]
@dmitriyse can you merged these 2 PR? I still don't understand why you separated them? And I still don't see any testing done for .NET Core target.

**Comment by dmitriyse** [comment]
> @dmitriyse can you merge these 2 PR? I still don't understand why you separated them? And I still don't see any testing done for .NET Core target.

@denfromufa 
Please see this comment https://github.com/pythonnet/pythonnet/pull/518#issuecomment-321095195

**Comment by dmitriyse** [comment]
Debug session finished. I need to fix points received from this session.
All such imports:
```CSharp
        [DllImport(_PythonDll, CallingConvention = CallingConvention.Cdecl)]
        internal static extern int PyDict_SetItemString(IntPtr pointer, string key, IntPtr value);
```
Should be modified to 
```CSharp
        [DllImport(_PythonDll, CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        internal static extern int PyDict_SetItemString(IntPtr pointer, string key, IntPtr value);
```
And other build script fixes.

**Comment by dmitriyse** [comment]
I managed to get EmbeddingTests works under NetCoreApp 2.0 target on all configurations except x86
x86 Support we can add later, once somebody will have enough time.

**Comment by dmitriyse** [comment]
Both targets (net40 and netcoreapp2.0) are build and tested in the same --xplat CI configuration. It's simpler to implement and saves some time on awaiting build result.

**Comment by dmitriyse** [comment]
Also I found a problem under NetCoreApp 2.0 - import "numpy" failed.

**Comment by dmitriyse** [comment]
This PR is ready for merging to the master. 
Current work allows to use python from the NetCoreApp 2.0 x64.

There are two main missing features, that can be implemented later:
1)  x86 Support for .NetCoreApp 2.0
2) Access to .NetCoreApp 2.0 libraries from the genuine python.

**Pull request merged**
