### PR TITLE
Rebased PR 450 (Py_Initialize without overriding signals)

### PR DESCRIPTION
**Pull request by filmor**
@rmadsen-ks 

### What does this implement/fix? Explain your changes.

Avoiding overriding signals from the application so that CTRL-C might be handled.

Using Py_InitializeEx(0) (instead Py_Initialize) to avoid overriding signals.

### Does this close any currently open issues?

#449 #450 

### Any other comments?

Just a rebased version of #450.

### Checklist

Check all those that are applicable and complete.

-   [ ] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [ ] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [ ] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by denfromufa** [comment]
@filmor why is this failing CI?

**Comment by filmor** [comment]
Something about `CSharpCodeProvider`, I'll look into it. It's the same error that @rmadsen-ks had already when he pushed the PR, I think.

**Comment by rmadsen-ks** [comment]
@filmor, the only change in this code is optionally calling InitializeEx instead of Initialize. This code is often being touched by tests. The actual change here is really simple, the unit test is excessively complex. Could you consider merging this without a unittest testing CTRL+C explicitly?

**Comment by filmor** [comment]
I think you are right. I'll merge the PR without the unit test using a merge commit, that way the test is at least present in the history.

**Pull request closed without merging**
