### PR TITLE
Improve Python <-> .NET exception integration

### PR DESCRIPTION
**Pull request by lostmsu**
### What does this implement/fix? Explain your changes.

1. .NET exceptions bubbled through Python stack back into .NET are preserved (before: `PythonException` was thrown instead).
2. Codecs can now encode and decode exceptions
3. .NET `InnerException` property is populated from Python's `__cause__` attribute.
4. Python exception stack is added to .NET exception stack
5. Internal: simplified memory management in `PythonException` class. Instead of working with raw pointers, uses `PyObject` instances.

### Breaking

1. `Traceback`, `PyVal` and `PyType` are now stored and returned as `PyObject`s.
2. `PythonException.Restore` no longer nulls out `PythonException` instance.
3. `PythonException` instances are no longer disposable. You can still dispose `.Type`, `.Value` and `.Traceback`, but it is not recommended, as they may be shared with other instances.

### Does this close any currently open issues?

#893, #1098

### Checklist

Check all those that are applicable and complete.

-   [x] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [x] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [ ] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by lostmsu** [comment]
Damn CI failures do not reproduce locally :/

**Comment by Felk** [comment]
Hello, given that `Exceptions` is not public anymore, what is the recommended way of catching specific python exceptions? Previously I used this:
```cs
catch (PythonException ex) when (ex.PyType == Exceptions.KeyError)
```

**Comment by lostmsu** [comment]
You can get `KeyError` from `builtins` module.

**Comment by Felk** [comment]
Thank you, this is how I got it to work now:
```cs
dynamic builtins = Py.Import("builtins");
try
{
    // ...
}
catch (PythonException ex) when (ex.Type.Equals(builtins.KeyError))
{
    // ...
}
```

**Comment by lostmsu** [comment]
@Felk comparing type handles will be slightly faster

**Comment by Felk** [comment]
@lostmsu can you give me an example of what you mean?

**Comment by lostmsu** [comment]
@Felk `ex.Type.Handle == builtins.KeyError.Handle`

**Pull request merged**
