### PR TITLE
Marshalling fix for 3-IntPtr args cdecl calls.

### PR DESCRIPTION
**Pull request by dmitriyse**
### What does this implement/fix? Explain your changes.
Workaround for the DotNet Core 2.0 marshaling bug.
Problem described here https://github.com/pythonnet/pythonnet/issues/96#issuecomment-329542908
...

### Does this close any currently open issues?

...

### Any other comments?

...

### Checklist

Check all those that are applicable and complete.

-   [ ] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [ ] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [ ] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by dmitriyse** [comment]
Related CoreCLR bug described here https://github.com/dotnet/coreclr/issues/14362

**Comment by dmitriyse** [comment]
It's a hot fix. That not fully solve the problem.
I created issue for the full solution https://github.com/pythonnet/pythonnet/issues/553

**Comment by denfromufa** [comment]
@dmitriyse is there any test for this "fix" or can you describe what issue you experienced? thanks for digging this through. also for the full potential fix in the future can you also describe a failing test?
finally this does not look like a bug in .net core, since this marshalling works as described in documentation.

**Comment by denfromufa** [comment]
@dmitriyse I just noticed that this fixed the issue that I experienced here: https://github.com/pythonnet/pythonnet/issues/96#issuecomment-329542908

let me verify it quickly.

**Comment by denfromufa** [comment]
@dmitriyse your fix is verified.

**Comment by denfromufa** [comment]
@filmor @vmuriart please review, I think this is good to go!

**Pull request merged**
