### PR TITLE
Fix for 3dsMax Python

### PR DESCRIPTION
**Pull request by dgsantana**
Importing clr in 3dsMax python, causes the application to crash on
GetTypes from certain assemblies.

### CODE REVIEW

**Comment by dgsantana** [comment]
There should be some error checking on the domain assembly lookup, to avoid "exploding", when running in some embed python dcc (in this case 3dsmax). This is what this pull request does.

**Comment by tonyroberts** [comment]
The travis and appveyor CI builds are failing with this error:

assemblymanager.cs(70,37): error CS1056: Unexpected character `$'

Could you refactor so as not to use C# 6 features please? (only a small change, and easier than converting the project to C# 6 for now)

thanks,
Tony

**Comment by dgsantana** [comment]
Sure no problem.

A Qui, 7 de Jan de 2016, 09:21, Tony Roberts <notifications@github.com>
escreveu:

**Comment by dgsantana** [comment]
Failing on AppVeyor py26, but not due to code changes.

**Comment by tonyroberts** [comment]
Sorry, I didn't notice before but this pull request is against the master branch. all pull requests need to be agains the develop branch (which is merged into master prior to a release).

**Comment by dgsantana** [comment]
Ok, I will make one against the develop. Are you guys using simple git flow
workflow?

Tony Roberts <notifications@github.com> escreveu no dia quinta, 7/01/2016
às 19:47:

**Comment by tonyroberts** [comment]
About as simple as it gets. The develop branch is for development; no problem accepting small commits directly on there, no need for a feature branch (although for more major features I would use a feature branch). Master is always buildable/releasable.

I'll move these commits to develop and create a new PR.

cheers,
Tony

**Comment by tonyroberts** [comment]
If I haven't screwed anything up your changes should now be in #115 :)

**Comment by dgsantana** [comment]
Thanks ;).

Tony Roberts <notifications@github.com> escreveu no dia quinta, 7/01/2016
às 21:13:

**Pull request closed without merging**
