### PR TITLE
Fix memory leaks due to spurious handle increment and add unit tests

### PR DESCRIPTION
**Pull request by williamsardar**
### What does this implement/fix? Explain your changes.
Fix memory leaks due to spurious handle increment and add unit tests
...

### Does this close any currently open issues?
Issue #691
...

### Any other comments?

...

### Checklist

Check all those that are applicable and complete.

-   [ x ] Make sure to include one or more tests for your change
-   [ x ] If an enhancement PR, please create docs and at best an example
-   [ x ] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [ x ] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by williamsardar** [comment]
Hi @denfromufa. How can I add the psutil dependency to the CI system?

**Comment by filmor** [comment]
There are probably more issues like this in the code, essentially every class derived from `ExtensionType` does not need an additional `Incref` as far as I can see, since the `PyType_GenericAlloc` call in the constructor will already lead to a refcount of 1.

**Comment by filmor** [comment]
Thank you very much for your contribution :)

**Comment by williamsardar** [comment]
@filmor thanks for the merge. Any indication as to when the next release might happen?

**Pull request merged**
