### PR TITLE
Fix missing Incref for Namespace and Assembly

### PR DESCRIPTION
**Pull request by testrunner123**
Fix crash of python interpreter 3.5 64-bit in garbage collector

### What does this implement/fix? Explain your changes.

If Python class is derived from .NET class and __namespace__ or __assembly__ attributes are set then python interpreter crashes in garbage collector. Provoke garbage collector run by:
```
import gc
gc.collect()
```

### Does this close any currently open issues?

#481 and may be others

### Checklist

Check all those that are applicable and complete.

-   [x] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [x] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [x] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by testrunner123** [comment]
Well, tests failed on mono with python 3.4. I have VM with Ubuntu 14.04 & mono 4.6 & python 3.4 64-bit.
But I can't exxecute tests, because pythonnet attempts to load "__Internal" library. I see that library exists, but not taken by Python.runttime.dll. Instead it trys to load "__Internal" DLL and take Py_IsInitialized() address. That fails in mono with exception: System.EntryPointNotFoundException : Py_IsInitialized

Any help how to get these tests runing?

**Comment by denfromufa** [comment]
@testrunner123 the tests are now passing on Travis CI (Mono). I'm not sure about your "__Internal" issue, maybe @vmuriart or @dmitriyse know?

**Comment by vmuriart** [comment]
@denfromufa are you closing and re-openning the issues to trigger the builds? You can re-trigger the builds on Travis/AppVeyor on each one's webpage. I think AppVeyor's had a bug though, or annoyance... I think you can only retrigger all Versions instead of just a couple specific ones.

@testrunner123 did you say this fixed #422 as well?

**Comment by testrunner123** [comment]
From src\test\test_subclass.py test_base_class, test_interface, test_derived_class work here. That is also what we used for interface with our assembly.

**Comment by testrunner123** [comment]
@denfromufa
Under "__Internal" issue I mean that pythonnet doesn't load python.so on Ubuntu. Instead it loads "__Internal". So impossible to run src\embed_tests on Ubuntu.

**Comment by denfromufa** [comment]
@testrunner123 i approved this pull request, but let's keep the original issue open due to this comment from @filmor. This bigger issue can be addressed in another pull request:

https://github.com/pythonnet/pythonnet/issues/481#issuecomment-306723709

Regarding "internal" let me test this locally. There is another non-reproducible issue with "internal": https://github.com/pythonnet/pythonnet/issues/445

**Comment by filmor** [comment]
Before merging, could you go through the checklist?

**Comment by testrunner123** [comment]
@denfromufa
It is more related #489

**Comment by denfromufa** [comment]
@testrunner123 can you please update changelog and authors list?

https://github.com/pythonnet/pythonnet/blob/master/AUTHORS.md
https://github.com/pythonnet/pythonnet/blob/master/CHANGELOG.md

**Comment by testrunner123** [comment]
@denfromufa
Done this. I also enabled first 3 subclass tests.

**Comment by lostmsu** [comment]
@filmor the fix seems to be merged. Can this bug be closed?

**Pull request merged**
