### PR TITLE
exception message passed from Python to .NET correctly

### PR DESCRIPTION
**Pull request by denfromufa**
https://github.com/pythonnet/pythonnet/issues/82

### CODE REVIEW

**Comment by tonyroberts** [comment]
Hi,

you need to be careful with reference counting when creating Python objects like this. Here you've create a new Python string object (_PyValueStr) but its reference count doesn't get decremented and so that object will never be deallocated.

If you use the PyObject .net class instead, in a using block, that will ensure it gets cleaned up correctly - for example the following should solve your problem without leaking any objects

```
        if ((_pyType != IntPtr.Zero) && (_pyValue != IntPtr.Zero))
        {
            using (PyObject pyType = new PyObject(_pyType))
            using (PyObject pyTypeName = pyType.GetAttr("__name__"))
            using (PyObject pyValue = new PyObject(_pyValue))
            {
                    string type = pyTypeName.ToString();
                    string value = pyValue.ToString();
                    _message = type + " : " + value;
            }
        }
```

The ToString method on PyObject does the string conversion, whereas Runtime.GetManagedString will only return a string of the Python object is a Python string.

Could be worth adding a unit test too, since now we have CI builds set up for most of the supported configurations.

cheers,
Tony

**Comment by denfromufa** [comment]
Is this unit test going to?

https://github.com/pythonnet/pythonnet/blob/master/src/tests/test_exceptions.py

**Comment by tonyroberts** [comment]
Hi,

yes that seems like a good place to put it,

cheers,
Tony

**Comment by tonyroberts** [comment]
This has been implemented in https://github.com/pythonnet/pythonnet/pull/88, so I think this one can be closed now. Please feel free to re-open if there's still an issue.

thanks!
Tony

**Comment by denfromufa** [comment]
Did the unit test get implemented too?

**Comment by tonyroberts** [comment]
Nope :( If you have one left over from your earlier work please feel free to open another PR.

thanks,
Tony

**Pull request closed without merging**
