### PR TITLE
Passing an arbitrary .NET object as the value of an attribute of PyObject

### PR DESCRIPTION
**Pull request by yagweb**
This implement the function of passing an arbitrary .NET object as attribute of PyObject by dynamic type. 

Four modifications are located at file pyobject.cs, the methods for dynamic type TryGetMember and TrySetMember were modified, a new method GetAttrDynamic was added for TryGetMember, and a new method SetAttrDynamic was added for TrySetMember.

Unit tests were given in a new file "src/embed_tests/dynamic.cs".

An Example was given in the discussion of issue [#370](https://github.com/pythonnet/pythonnet/issues/370) , the Solution 4.

/***********Information below is outdated and can be removed*************/

However this doesn't fix the issue [why sys.stdout returned null #370](https://github.com/pythonnet/pythonnet/issues/370)
...
...

I don't know where to put the test, so I put it here. If needed, it can be added to Embedded tests with some work.

```
    class dynamicTest
    {
        public void Test()
        {
            var output = new Output();
            using (Py.GIL())
            {
                dynamic sys = Py.Import("sys");
                sys.stdout = output; //Now it's working

                //function test, print in python
                PythonEngine.RunSimpleString("print('Hello!')");

                //Check whether there are the same object
                var result1 = sys.stdout == output;
                Console.WriteLine($"Compare in .NET: {result1}");  //Output True   

                //Check whether we can get the attr of a python object 
                //when the value of attr is not a .NET object
                PythonEngine.RunSimpleString("import sys\n" +
                "from io import StringIO\n" +
                "sys.stderr = StringIO()\n");
                var bb = sys.stderr;
                bb.write("Hello!\n");
                Console.Write(bb.getvalue());

                /********Pass the .NET object in Python side*********/
                PythonEngine.RunSimpleString("import sys\n" +
                "from io import StringIO\n" +
                "sys.stderr = sys.stdout\n");
                //Compare in Python
                PythonEngine.RunSimpleString("import sys\n" +
                "print('Compare in Python: %s' % (sys.stderr is sys.stdout))\n");  //Output False

                //compare in .NET
                var result2 = sys.stdout == sys.stderr;
                Console.WriteLine($"Compare in .NET: {result2}");  //Output True

                /*********Pass the .NET object in .NET side********/
                sys.stdout = sys.stderr;
                //Compare in Python
                PythonEngine.RunSimpleString("import sys\n" +
                "print('Compare in Python: %s' % (sys.stderr is sys.stdout))\n");  //Output False

                //compare in .NET
                var result3 = sys.stdout == sys.stderr;
                Console.WriteLine($"Compare in .NET: {result3}");  //Output True    

                /*********When the .NET object was created in Python side*****************/
                PythonEngine.RunSimpleString(@"
import sys
from Test import Output
sys.stderr = Output()
");
                var aa = sys.stderr; //Return the .NET object, not a PyObject with an IntPtr
                aa.write("Hello!\n");            
            }
        }
    }
    public class Output
    {
        public void write(String str)
        {
            //str = str.Replace("\n", Environment.NewLine);
            Console.Write(str);
        }

        public void writelines(String[] str)
        {
            foreach (String line in str)
            {
                Console.Write(str);
            }
        }
        public void flush() { }
        public void close() { }
    }
```

### CODE REVIEW

**Comment by denfromufa** [comment]
@yagweb i like this PR, the test looks good and can be added to embedded tests. Let us know if you need any help?

**Comment by vmuriart** [comment]
Reviewing now. I just pushed some whitespace changes to the `pr` to avoid dealing with those later.
@yagweb I'm adding the unittest you included above as well.

**Comment by yagweb** [comment]
@denfromufa @vmuriart Thank you for your Response. I have added the unittest and fixed a bug of assigning null to the attribute of a pyobject. I'll commit it later.

**Comment by vmuriart** [comment]
@yagweb no problem. I'll stash my changes then.

**Comment by yagweb** [comment]
@denfromufa  @vmuriart I am sorry the commits are a little mess, because in the start I did not create a branch for this modification and directly worked on my master branch. I will merge them later.

The AssignObjectInPython has a very strange error, but it works well when I called it in my C# code directly, so I just ignore it.

**Comment by vmuriart** [comment]
@yagweb whats the error you are seeing?

**Comment by vmuriart** [comment]
irt the commit history, you can `squash` and `force-push` to cleanup your history.

**Comment by yagweb** [comment]
@vmuriart Thank you for your help. The commits have been squashed.

The error occurs when creating a .NET object in python, and It disappeared when I try to debug with calling it in my C# code.

The error information is,
```
Python.EmbeddingTest.dynamicTest.AssignObjectInPython:
System.OverflowException : Arithmetic operation resulted in an overflow.
```
and the traceback is,
```
at System.IntPtr.op_Explicit(IntPtr value)
at Python.Runtime.ManagedType.GetManagedObject(IntPtr ob) in D:\git\pythonnet\src\runtime\managedtype.cs:line 31
at Python.Runtime.ClassObject.tp_new(IntPtr tp, IntPtr args, IntPtr kw) in D:\git\pythonnet\src\runtime\classobject.cs:line 53
at e__NativeCall.Call_3(IntPtr , IntPtr , IntPtr , IntPtr )
at Python.Runtime.NativeCall.Call_3(IntPtr fp, IntPtr a1, IntPtr a2, IntPtr a3) in D:\git\pythonnet\src\runtime\nativecall.cs:line 128
at Python.Runtime.MetaType.tp_call(IntPtr tp, IntPtr args, IntPtr kw) in D:\git\pythonnet\src\runtime\metatype.cs:line 154
at Python.Runtime.Runtime.PyRun_SimpleString(String code)
at Python.Runtime.PythonEngine.RunSimpleString(String code) in D:\git\pythonnet\src\runtime\pythonengine.cs:line 120
at Python.EmbeddingTest.dynamicTest.AssignObjectInPython() in D:\git\pythonnet\src\embed_tests\dynamic.cs:line 68
```

**Comment by vmuriart** [comment]
Looks like you found a bug for us! https://www.codeproject.com/Questions/528923/Howplustoplusfix-aplus-OverflowExceptionplusocc

Most likely the link above is the issue/fix. I'll take a look tomorrow to make sure and fix it on master.

**Comment by yagweb** [comment]
@vmuriart I found a way to reproduce the bug. Just call that unit test function twice, at the second call, this exception will occur. The following code can do this. Hope this can help you to fix it.

```

namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {            
            PythonEngine.Initialize();
            using (Py.GIL())
            {
                PythonEngine.RunSimpleString(@"
import sys
from Test import outstream
sys.stdout = outstream()
");
            }
            PythonEngine.Shutdown();

            PythonEngine.Initialize();
            using (Py.GIL())
            {
                PythonEngine.RunSimpleString(@"
import sys
from Test import outstream
sys.stdout = outstream()
");    //**exception will occor here！**
            }
            PythonEngine.Shutdown();
        }
    }
    
    public class outstream { }
}
```

**Comment by vmuriart** [comment]
Just pushed a [`fixup!`](http://fle.github.io/git-tip-keep-your-branch-clean-with-fixup-and-autosquash.html) to the branch to merge with the first commit. Just wanted to clarify in case you hadn't seen one of those before and thought I was being rude 😄 .

**Comment by vmuriart** [comment]
@yagweb got an update. I formatted/clean-up the code, and fixed the overflow bug on #376. Once its merged, I recommend `squash` all commits here and `rebase` ontop of `master`. I can do this for you and `force-push` the changes here if you want.

The test is still failing though, #376 just allowed the exception underlying exception to bubble up. This is the [error](https://ci.appveyor.com/project/vmuriart/pythonnet/build/pr373-rb-1069/job/axmv92k3vxfox0c7#L506) i'm seeing now. 

The error you are seeing above when doing `Initialize`, `Finalize`, `Initialize`, is the vain of my existence 👎. #343 and #365 are examples of similar issues that gave similar errors. They occur because there is an underlying exception that we didn't handle and it causes the 2nd `initialize` to fail.

**Comment by yagweb** [comment]
@vmuriart another bug of this PR has been fixed. I will try to squash all commits and rebase ontop of master by myself first.

**Comment by yagweb** [comment]
@denfromufa @vmuriart During developing the unittests, I found it's hard to evaluate a python expression and obtain the results. So I modified the PythonEngine.RunString method, add a new class called PySession. Now I can do this:

```
using (var ps = new PySession())
{
    var result = ps.Eval("1+2"); //return 3

    dynamic sys = ps.Import("sys");  //import, it will also be added in globals
    ps.SetLocal("stdout", new Output()); //declare a local variable
    ps.Exec("sys.stdout = stdout");  //it's working!
    ps.Exec("print('Hello!')");

    sys.stderr = 12;
    ps.Exec("print(sys.stderr+1)");

    ps.SetGlobal("bb", 100);//declare a global variable
    ps.SetLocal("cc", 10);//declare a local variable
    ps.Exec("aa=bb+cc+3");   
    var aa = ps.Get("aa"); //return 113
    Console.WriteLine(aa);
}
```
what do you think about? I'm not familiar with git, I'll try to create a new branch and create a new PR for this later.

**Comment by denfromufa** [comment]
@yagweb regarding PySession can you please open an issue first, so that we can quickly iterate on purpose, design and API. You can open a pull request, but it may get affected by decisions in the issue. I think this  closely resembles the Scopes in IronPython.

**Comment by vmuriart** [comment]
@yagweb I think you are missing a reference to `<Reference Include="Microsoft.CSharp" />` on `EmbeddingTest.csproj`. Probably got lost in the merge conflict resolution.

**Comment by yagweb** [comment]
@denfromufa Thank you for your suggestion, I opened the issue [here](https://github.com/pythonnet/pythonnet/issues/380).

**Comment by yagweb** [comment]
@vmuriart Thank you, I  have squashed this commit.

**Comment by vmuriart** [comment]
pushed a fixup to minimize whitespace/encoding changes. 
From your other `pull_request` it sounds like `AssignObjectInPython` test is no longer needed and consequentially neither would `outstream` be needed?

**Comment by yagweb** [comment]
@denfromufa @vmuriart I read some source code, and found pythonnet already had some powerful methods. So, this branch undergo a major revision. Please check it again.

1. the GetAttrDynamic and SetAttrDynamic method is deleted.
2. the TrySetMember should call set attribute method of CPython no matter it has the attribute or not. Because python object is dynamic. If not, a new attribute cannot be found in CPython.
3. Corresponding to the TrySetMember method, the TryGetMember method only get attribute from CPython.

The unit tests file also changed. The AssignObjectInPython has been removed and the outstream class has been replace with the StringBuilder class.

**Comment by yagweb** [comment]
@vmuriart The method AssignObjectInPython can be removed. but taking the bug it found,  I think a new unit test method below could be to the file pyinitialize.cs.
```
[Test]
[Ignore("System.ArgumentException : Cannot pass a GCHandle across AppDomains")]
public void Main()
{
    PythonEngine.Initialize();
    using (Py.GIL())
    {
        PythonEngine.RunSimpleString(
            "import sys\n"+
            "from System.Text import StringBuilder\n"+
            "sys.attr1 = StringBuilder()\n");
    }
    PythonEngine.Shutdown();

    PythonEngine.Initialize();
    using (Py.GIL())
    {
        PythonEngine.RunSimpleString(
            "import sys\n" +
            "from System.Text import StringBuilder\n" +
            "sys.attr1 = StringBuilder()\n");
    }
    PythonEngine.Shutdown();
}
```

The code below can achieve the same functionality but with no error. It reveals that,
1. We should avoid new .NET object in Python when the host is a .NET program.
2. This may cause by CPython new .NET object in a new .NET environment, not in the current one.(unprecise)。Maybe it can help to resolve this bug.
```
[Test]
public void Main2()
{
    PythonEngine.Initialize();
    using (Py.GIL())
    {
        dynamic sys = PythonEngine.ImportModule("sys");
        sys.attr1 = new StringBuilder();
    }
    PythonEngine.Shutdown();

    PythonEngine.Initialize();
    using (Py.GIL())
    {
        dynamic sys = PythonEngine.ImportModule("sys");
        sys.attr1 = new StringBuilder();
    }
    PythonEngine.Shutdown();
}
```

**Comment by vmuriart** [comment]
@yagweb thanks for taking the time to digging more into that bug. It looks to be an extension of #343. Your test is very similar to the one in [`pyinitialize`](https://github.com/pythonnet/pythonnet/blob/0f00e3a995d1d00d863ce9c170f8809722bcf1c9/src/embed_tests/pyinitialize.cs#L30-L38) so I'll probably add the test there.

Is the issue only present when using `StringBuilder()` or can it be any arbitrary object? (ie. a string?).

**Comment by yagweb** [comment]
@vmuriart I tried several RunSimpleString combinations in the two Initialize. If keep the two RunSimpleString statement the same, System.Int32 and System.String can also trigger this exception. If the .NET object created in the two RunSimpleString statement are different, some can trigger the exception, some cannot.
So I think it can be any arbitrary object. I updated my last comment to make the test simpler.

**Comment by vmuriart** [comment]
@yagweb sorry it took me a while to review, I kept getting distracted while reviewing this. 
Looks good. Just rebased it and will merge once all CI checks complete. 

irt the other issue. We should open a new issue to summarize the findings.

**Comment by yagweb** [comment]
@vmuriart I got the merged message. I will rebase my branches. Thank you!

**Comment by vmuriart** [comment]
No worries. I had to rebase it because I updated the `CHANGELOG` and introduced a merge conflict. Also gave me a chance to clean up some whitespacing :nerd_face:

**Pull request merged**
