### PR TITLE
allow .NET classes to override __getattr__ and __setattr__

### PR DESCRIPTION
**Pull request by lostmsu**
### What does this implement/fix? Explain your changes.

This enables .NET classes to override `__getattr__` and `__setattr__` by implementing `IGetAttr` and `ISetAttr` interfaces correspondingly.

### How does it work

When constructing a Python type, that will represent C# type, if the C# type implements one of the interfaces, fill corresponding slots in the Python type with custom handlers for `tp_getattro` or `tp_setattro` with implementations from `slots.cs`.

### Checklist

Check all those that are applicable and complete.

-   [x] Make sure to include one or more tests for your change
-   [x] If an enhancement PR, please create docs and at best an example
-   [x] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [x] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### P.S.
This is a single-commit change. Probably could be cherry-picked merged without a merge commit.

### CODE REVIEW

**Comment by lostmsu** [comment]
Looks like .csproj files have varying line endings. Do you guys know how to enforce them in the future?

**Comment by lostmsu** [comment]
@filmor any idea why that change could have broken x86 tests? I just tried to run Python.EmbeddingTest on Windows with x86, and did not get any crashes or issue? Could it be, that a simple rerun needed (then how to do it?)?

**Comment by filmor** [comment]
It looks good now. Regarding the file endings: IMO we should always have Unix style line-endings everywhere. We could set up a `.gitattributes` file for this (like outlined here: https://stackoverflow.com/questions/170961/whats-the-best-crlf-carriage-return-line-feed-handling-strategy-with-git), be my guest :)

**Comment by lostmsu** [comment]
@filmor I don't think it does. x86 builds are still failing in appveyor (unlike, for example, trivial C# version change).

**Comment by lostmsu** [comment]
Damn, Hyper-V on Windows 10 does not boot x86 linuxes (tried Ubuntu 16.04, 18.04 and the latest Debian)

**Comment by lostmsu** [comment]
Closing this out, as we decided on ad-hoc approach instead (e.g. one should simply have a `__getattr__` method in .NET if he wants to override Python's `__getattr__`).

**Pull request closed without merging**
