### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by Cronan**
Added fix for looking up types (in #622)

### CODE REVIEW

**Comment by denfromufa** [comment]
@Cronan can you add a link to corresponding pull request or commit or issue?

**Comment by Cronan** [comment]
@denfromufa Sorry, done

**Comment by Cronan** [comment]
@denfromufa Gah, done o_O

**Comment by denfromufa** [comment]
@Cronan can you please include this pull request as part of https://github.com/pythonnet/pythonnet/pull/622

this is our normal workflow (you can see that from template)

**Comment by Cronan** [comment]
Included as part of #622

**Pull request closed without merging**
