### PR TITLE
Build system improvements pack - addressing comments to PR and some issues.

### PR DESCRIPTION
**Pull request by dmitriyse**
### What does this implement/fix? Explain your changes.
Fixes issues specified in reviews for PR #518 and PR #519 and fix for the issue https://github.com/pythonnet/pythonnet/issues/539

### Does this close any currently open issues?
https://github.com/pythonnet/pythonnet/issues/539
...

### Any other comments?

...

### Checklist

Check all those that are applicable and complete.

-   [ ] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [ ] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [ ] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by dmitriyse** [comment]
Please do not review this branch, until I commit and test all part of the solution.
I will notify when this branch will be ready to review and merge.

**Comment by denfromufa** [comment]
@dmitriyse please use [WIP] in your PR title when it is Work In Progress.

**Comment by dmitriyse** [comment]
Thank you for the tip.

**Comment by dmitriyse** [comment]
PR is ready !
1) All comments to #518 addressed.
2) DotNet 2.0/ Net4.0    pdb,debug build options for Debug/Release configuration now specified correctly.
(fixes problem when release builds for dotnet core 2.0 generates windows PDB format instead of portable pdb format)
3) Fix for the https://github.com/pythonnet/pythonnet/issues/539 issue
4) PYTHONNET_INTEROP_FILE env var introduced to allow working with custom interop*.cs file inside IDE.
5) pythonnet.15.sln is tested with Project Rider 2017.1.2 and result is "FULL SUPPORT".
  So we should plan when we remove "classic build" or at least make --xplat build as a default.

**Comment by dmitriyse** [comment]
It's so good to be a member of the core team, now I can kill broken builds without waiting. :)

**Comment by denfromufa** [comment]
@dmitriyse i think this is good to merge! if @vmuriart can take a quick look at code coverage failures, that's great, but that is not blocking this PR merge.

**Pull request merged**
