### PR TITLE
remove remoting block for .NET standard

### PR DESCRIPTION
**Pull request by koubaa**
### What does this implement/fix? Explain your changes.

Remove remoting support

### Does this close any currently open issues?

Removes some dependency on .NET framework

### Any other comments?

...

### Checklist

Check all those that are applicable and complete.

-   [ ] Make sure to include one or more tests for your change
-   [x] If an enhancement PR, please create docs and at best an example
-   [x] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [x] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by lostmsu** [comment]
If this is the only line where it is used, can we replace it with runtime feature detection instead of completely removing a feature?

E.g.
```csharp
static readonly Func<object, bool> IsTransparentProxy = GetIsTransparentProxy();

static bool Never(object _) => false;

static Func<object, bool> GetIsTransparentProxy() {
  var remoting = typeof(int).Assembly.GetType("System.Runtime.Remoting.RemotingServices");
  if (remoting is null) return Never;

  var isProxy = remoting.GetMethod("IsTransparentProxy", new []{typeof(object)});
  if (isProxy is null) return Never;

  return (Func<object, bool>)Delegate.CreateDelegate(
    typeof(Func<object, bool>), isProxy,
    throwOnBindFailure: true);
}
```

P.S. @filmor Travis CI results are not being picked up...

**Comment by koubaa** [comment]
@lostmsu its a good idea but this isn't a tested feature and I don't want to build a test for it.  Are you confident your code will work without tests?

**Comment by lostmsu** [comment]
@koubaa the calls to this method probably have some coverage, so if it crashes, we should see in CI. The feature itself might be broken with this, but IMO it is better, than removing it completely.

**Comment by koubaa** [comment]
@lostmsu as long as I'm not signing up for testing remoting, I am ok with that.  I'll push an update with your change and remove the changelog entry

**Comment by lostmsu** [comment]
@koubaa , yeah, let's do that.

**Pull request merged**
