### PR TITLE
Add __version__

### LINKED ISSUE #67: version/build number
setup version/build number

### PR DESCRIPTION
**Pull request by vmuriart**
Closes #67, #218.

### CODE REVIEW

**Comment by vmuriart** [comment]
For reference, below is the alternative method I been using to detect the currently installed version.

```python
def pythonnet_version():
    # Based from: http://stackoverflow.com/a/23885252
    import pip

    for x in pip.get_installed_distributions():
        if x.key == "pythonnet":
            return x.version
```

**Comment by tonyroberts** [comment]
Would it be simpler to add __version__ to clr.py (in src/runtime/resources)? Everything in that file gets added to the clr module in Initialize. A small change would be needed as currently Initialize ignores anything starting with an underscore.

**Comment by vmuriart** [comment]
That would make more sense. Let me review and try that out. thanks!

**Comment by vmuriart** [comment]
@tonyroberts thanks for the feedback, it worked

**Comment by filmor** [comment]
It would be a lot nicer (and more future proof) if this information was taken during the build process from either a version file or the git repository (e.g. using https://github.com/warner/python-versioneer).

**Comment by denfromufa** [comment]
I agree with @filmor - we need automated way of updating versions. One trigger (e.g. Github release tag) should make changes in setup.py and `__version__`.

**Comment by vmuriart** [comment]
I agree, I was thinking along the same lines and was inclining towards [bumpversion](https://github.com/peritus/bumpversion). 

In the interest of separations of concerns though, can we merge this `pr` and I'll open a ticket to add the automation.

**Comment by denfromufa** [comment]
If this PR does not conflict with either of these automated versioning
tools, then I agree - we can merge.

**Pull request merged**
