### PR TITLE
Catch any unhandled exceptions in TryConvertArgument

### PR DESCRIPTION
**Pull request by jmlidbetter**
### What does this implement/fix? Explain your changes.

Fixes Issue #933

### Does this close any currently open issues?

#933

### Any other comments?

TryConvertArgument ought not to throw any exceptions - exceptions => failure to convert so should do so gracefully.

### Checklist

Check all those that are applicable and complete.

-   [x] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [x] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [x] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by Cronan** [comment]
@filmor OK to merge?

**Comment by filmor** [comment]
I'll have another look and merge pending PRs after I'm back from vacation next week

**Comment by Cronan** [comment]
Thanks muchly. Hope you’re having a good time.

**Comment by lostmsu** [comment]
This is a very poor solution to the problem, as it masks any real conversion problems, that might occur.
From the first look `ToArray` should explicitly check for this scenario.

**Comment by jmlidbetter** [comment]
> 
> 
> This is a very poor solution to the problem, as it masks any real conversion problems, that might occur.
> From the first look `ToArray` should explicitly check its inputs to handle #933 , or `ToManagedValue` should to the same before calling `ToArray`.

**Comment by jmlidbetter** [comment]
> 
> 
> This is a very poor solution to the problem, as it masks any real conversion problems, that might occur.
> From the first look `ToArray` should explicitly check its inputs to handle #933 , or `ToManagedValue` should to the same before calling `ToArray`.

I do partially agree with you that this should be handled at a lower level and you're more than welcome to propose such a fix yourself. Ultimately, however, a "TryXYZ" should not crash the python interpretter. If it returns False an error will get propogated through the correct channels and the user can report bugs as necessary. In my opinion, crashing the interpretter is a truly last resort and should be avoided at all costs. NB python is not like C# - often people will be running things in, for example,  stateful jupyter notebooks where a crash can destroy (rightfully or otherwise) hours of work.

**Comment by lostmsu** [comment]
@jmlidbetter handling all exceptions can lead to something worse, than a crash: data corruption. You'd rather know there was a problem and redo 2 hours of work, than silently use flawed analysis results for years, until the consequences of corrupted data hit you in the face.

**Comment by Cronan** [comment]
@jmlidbetter and I have discussed this in depth - the current state of pythonnet as far as uncaught exceptions go is not good - there are many places where non-fatal exceptions can bubble all the way to the top, which causes a segfault, and the Python interpreter to die.

This makes the library look flaky, and makes people waste time digging into hard to diagnose errors.
This kind of error should be writing warnings and errors to stdout (or better, to the python log), not causing the interpreter to crash. That should be reserved for genuinely fatal cases, as mentioned by @lostmsu above.

The reason this is in a PR because this specific case causes an interpreter crash in one of the tests in .NET Core.

**Comment by lostmsu** [comment]
@Cronan at least me & @filmor agree about bad smell of the code, that swallows all exceptions.

I've already proposed one option: to handle this case in the downstream array converter. Another is to go up to `MethodBinder.Invoke`, and wrap the whole method in `try - catch` block, and in the `catch` use `Exceptions.SetError`

**Comment by Cronan** [comment]
That all sounds good, and I’m sure someone will get to this at some point, we’ve got no further time to work on this right now - we’ve patched it in our fork.

**Pull request closed without merging**
