### PR TITLE
Updating nuget to 3.5.0

### PR DESCRIPTION
**Pull request by cowboygneox**
When trying to pull `pythonet-2.1.0` using `pip` on Mac OS X, I was getting the stack below. 
Updating `nuget` to 3.5.0 resolved my issue.

I updated `nuget` using:

```
$ mono tools/nuget/nuget.exe update -self
```

```
$ pip install pythonnet
Collecting pythonnet
  Using cached pythonnet-2.1.0.zip
Building wheels for collected packages: pythonnet
  Running setup.py bdist_wheel for pythonnet ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/0x/gzzhn14j3sb7vxr4xtq6kzsw0000q9/T/pip-build-rchCEW/pythonnet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/0x/gzzhn14j3sb7vxr4xtq6kzsw0000q9/T/tmpt7IZ1fpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  Unable to find version '2.6.2' of package 'NUnit'.
  Unable to find version '1.2.6' of package 'UnmanagedExports'.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/0x/gzzhn14j3sb7vxr4xtq6kzsw0000q9/T/pip-build-rchCEW/pythonnet/setup.py", line 357, in <module>
      setup_requires=setup_requires
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/Library/Python/2.7/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
      self.run_command(cmd_name)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 337, in run
      self.build_extensions()
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 446, in build_extensions
      self.build_extension(ext)
    File "/private/var/folders/0x/gzzhn14j3sb7vxr4xtq6kzsw0000q9/T/pip-build-rchCEW/pythonnet/setup.py", line 122, in build_extension
      self._install_packages()
    File "/private/var/folders/0x/gzzhn14j3sb7vxr4xtq6kzsw0000q9/T/pip-build-rchCEW/pythonnet/setup.py", line 231, in _install_packages
      check_call(cmd, shell=use_shell)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe restore pythonnet.sln -o packages' returned non-zero exit status 1

  ----------------------------------------
  Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
  Running setup.py install for pythonnet ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/0x/gzzhn14j3sb7vxr4xtq6kzsw0000q9/T/pip-build-rchCEW/pythonnet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/0x/gzzhn14j3sb7vxr4xtq6kzsw0000q9/T/pip-wSsRhI-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    Unable to find version '2.6.2' of package 'NUnit'.
    Unable to find version '1.2.6' of package 'UnmanagedExports'.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0x/gzzhn14j3sb7vxr4xtq6kzsw0000q9/T/pip-build-rchCEW/pythonnet/setup.py", line 357, in <module>
        setup_requires=setup_requires
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/install.py", line 53, in run
        return _install.run(self)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 573, in run
        self.run_command('build')
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 337, in run
        self.build_extensions()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 446, in build_extensions
        self.build_extension(ext)
      File "/private/var/folders/0x/gzzhn14j3sb7vxr4xtq6kzsw0000q9/T/pip-build-rchCEW/pythonnet/setup.py", line 122, in build_extension
        self._install_packages()
      File "/private/var/folders/0x/gzzhn14j3sb7vxr4xtq6kzsw0000q9/T/pip-build-rchCEW/pythonnet/setup.py", line 231, in _install_packages
        check_call(cmd, shell=use_shell)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe restore pythonnet.sln -o packages' returned non-zero exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/0x/gzzhn14j3sb7vxr4xtq6kzsw0000q9/T/pip-build-rchCEW/pythonnet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/0x/gzzhn14j3sb7vxr4xtq6kzsw0000q9/T/pip-wSsRhI-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/0x/gzzhn14j3sb7vxr4xtq6kzsw0000q9/T/pip-build-rchCEW/pythonnet/
```

```
$ mono --version
Mono JIT compiler version 4.6.2 (mono-4.6.0-branch/ac9e222 Wed Dec 14 17:02:09 EST 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug
	LLVM:          yes(3.6.0svn-mono-master/8b1520c)
	GC:            sgen
```

### CODE REVIEW

**Comment by cowboygneox** [comment]
Can we merge this and get a build out asap so I don't have to maintain this within my project?

**Comment by vmuriart** [comment]
I take my previous statement back, `nuget` update [runs as part of the build](https://github.com/pythonnet/pythonnet/blob/9c060a31d0cb795ad3e8f9ebc9c0fdaec5d4f8fb/setup.py#L238). 

There may be something else going on preventing the update to happen.

**Comment by filmor** [comment]
That's also what I experienced, however, I don't see a problem with updating the builtin version of nuget once in a while.

**Comment by vmuriart** [comment]
@filmor I have no issue with updating the binary. What I find curious is that the update that is run as part of the build is silently failing, and updating the binary here masks that. 

Ideally we [shouldn't have to include](https://web.archive.org/web/20160824224654/http://wiki.team-mediaportal.com/2_MEDIAPORTAL_2/8_Contribute/Development/Code_Guidelines/Avoiding_Binaries/Prepare_a_git_repo_for_NuGet) the `nuget.exe` file at all, but it seems [mono](http://stackoverflow.com/questions/19072529/nuget-how-to-configure-package-restore-on-monodevelop-xamarin-studio) doesn't play nice with the restore.

**Comment by vmuriart** [comment]
I'm ok merging this though, I'll submit a `pr` later if i figure out a way to do it without including the binary.

**Comment by denfromufa** [comment]
@cowboygneox do you agree to transition from Zope to MIT license?

**Comment by filmor** [comment]
Since this isn't actually a copyrightable contribution, I think it's fine to merge this even without the explicit agreement.

**Comment by vmuriart** [comment]
@filmor agreed.

**Comment by cowboygneox** [comment]
I appreciate the fast response. Thanks guys!

**Pull request merged**
