### PR TITLE
MIT License

### LINKED ISSUE #234: Update License - MIT
I'm not sure about the entire history of the license, but it looks to have been chosen when the project originally was hosted on the zope.org community site. 
As the project as grown, I think its time to update the license to one that provides the [same rights and protections](https://tldrlegal.com/license/zope-public-license-2.0-%28zpl-2.0%29#summary) but its more commonly known [BSD 3-clause](https://tldrlegal.com/license/bsd-3-clause-license-%28revised%29)

~~As very minimum I would like to update the license from the current [zope 2.0](https://tldrlegal.com/license/zope-public-license-2.0-%28zpl-2.0%29#fulltext) to its more friendly written revision [zope 2.1](https://tldrlegal.com/license/zope-public-license-2.1-%28zpl-2.1%29#fulltext)~~

The license proposed is MIT License. 

---

MIT license - list of contributors and status on approval:
- [ ] @tiran
- [x] @ArvidJB
- [x] @BartonCline
- [x] @bltribble
- [x] @brianlloyd
- [x] @davidanthoff
- [x] @denfromufa 
- [x] @dgsantana
- [x] @dlech
- [x] @dmitriyse
- [x] @fdanny 
- [x] @filmor
- [x] @hsoft (github) #hardcoded (sourceforge)
- [x] @jfrayne (Joe Frayne from sourceforge)
- [x] @jreback
- [x] @johnburnett 
- [x] @leith-bartrich
- [x] @lstratman
- [x] @matthid
- [x] @omnicognate
- [x] @patstew
- [x] @rico-chet 
- [x] @rmadsen-ks 
- [x] @rnestler
- [x] @sdpython
- [x] @stonebig 
- [x] @sweinst
- [x] @swinstanley
- [x] @t3476
- [x] @tonyroberts
- [x] @vmuriart
- [x] @zanedp

### PR DESCRIPTION
**Pull request by vmuriart**
Closes #234

### CODE REVIEW

**Comment by filmor** [comment]
It could make sense to add an `AUTHORS` file to make the exact copyright holders clear.

**Comment by denfromufa** [comment]
@vmuriart how about setup.py?

https://github.com/pythonnet/pythonnet/blob/master/setup.py#L348

**Comment by denfromufa** [comment]
many other places:

https://github.com/pythonnet/pythonnet/search?utf8=%E2%9C%93&q=zope

**Comment by vmuriart** [comment]
I noticed it as wel went I was cleaning out the project.
Many of those references are removed in the other pull request I have since
they are outdated files.
If we merge that branch in first I'll clean out what's left over on this
one

On Mon, Jan 9, 2017 at 09:48 denfromufa <notifications@github.com> wrote:

many other places:


https://github.com/pythonnet/pythonnet/search?utf8=%E2%9C%93&q=zope




—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pythonnet/pythonnet/pull/314#issuecomment-271337463>,
or mute the thread

**Comment by vmuriart** [comment]
@denfromufa I just updated the files that will remain after #320 is merged and opened a `pr` for the homepage as well pythonnet/pythonnet.github.io#6

**Comment by vmuriart** [comment]
@filmor we could use the list from #234 for it. Not sure if we are missing anyone for the last set of commits.

**Comment by filmor** [comment]
Yep, sounds like a good start, recent history can easily be checked.

**Comment by vmuriart** [comment]
`AUTHORS.md` added with everyone from the #234 and by doing a quick glance through the recent commits.

**Comment by bltribble** [comment]
It couldn't hurt to ping @tiran again just to make sure he has another opportunity to push back against this change if so desired.

**Comment by vmuriart** [comment]
@bltribble I e-mailed him once more before merging this in to make sure, still no response ☹️ maybe you'll have better luck?

**Comment by vmuriart** [comment]
I think he's active on twitter if anyone wanted to try that...

**Comment by bltribble** [comment]
I emailed him at his redhat email address.

"Speak now or forever hold your peas."

**Comment by denfromufa** [comment]
I tweeted @tiran on Twitter before. I emailed his both email accounts
before.

**Comment by stonebig** [comment]
We'll never know the reason of this silence, but it's equivalent as a commitment, as he is even keeping active on Github.

**Pull request merged**
