### PR TITLE
Removes imports deprecated in Python3

### LINKED ISSUE #924: Python2 deprecated native method import
### Environment

-   Pythonnet version: latest
-   Python version: 3.7.4
-   Operating System: MacOS 10.14.6

### Details 

-   Compiling under xcode for iOS, it throughs PyClass_New reference not found error.
     After diggin' around for a while, there is no PyClass_New definition in Python3 actually.
    Also there are other deprecated python3 APIs need to be nested in #if PYTHON2 condition.

     PyLong_GetMax(not exists)
     PyObject_GC_New(name error, should be _PyObject_GC_New)
    

```
[DllImport(_PythonDll, CallingConvention = CallingConvention.Cdecl)]
 internal static extern IntPtr PyClass_New(IntPtr bases, IntPtr dict, IntPtr name);
```

### PR DESCRIPTION
**Pull request by Cronan**
### What does this implement/fix? Explain your changes.
A small number of existing imports are deprecated in Python3. 
This removes them or compiles them out.

### Does this close any currently open issues?
Fixes #924 
...

### Any other comments?

N/A

### Checklist

Check all those that are applicable and complete.

-   [N/A] Make sure to include one or more tests for your change
-   [N/A] If an enhancement PR, please create docs and at best an example
-   [X] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [X] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by Cronan** [comment]
@filmor Any idea why the build is broken?

**Comment by filmor** [comment]
The Appveyor build just timed out for one part, I triggered it again and it seems to work fine now. The Travis build looks a bit trickier, the Mono version pulled in seems to be broken...

**Comment by filmor** [comment]
Meh, the travis error is broken. The symbol it is missing is `_ZTIPi` which is the C++ type info for `int*`, so maybe there are incompatible C++ ABIs at play here ...

**Comment by Cronan** [comment]
How can the build just break? Were there changes made?

**Comment by filmor** [comment]
The mono version is not pinned right now, so since the 18th we pull in mono 6. I'll see whether I can lock us to 5.20 for now.

**Comment by Cronan** [comment]
Good spot, thank you

**Comment by Cronan** [comment]
@filmor Can be merged?

**Comment by filmor** [comment]
Yeah, looks good to me. @lostmsu Be aware of this one if you are looking into switching to delegates.

**Pull request merged**
