### PR TITLE
Allow formatting an exception with traceback.format_exception

### PR DESCRIPTION
**Pull request by slide**
### What does this implement/fix? Explain your changes.

This implements the ability to format an exception using traceback.format_exception. This is very useful for when you are embedding Python into an application and want to show the Python exception similar to how it would be printed in the Python console.

### Does this close any currently open issues?

None that I know of.

### Checklist

Check all those that are applicable and complete.

-   [x] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [X] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by slide** [comment]
From looking at the logs for the travis builds, it seems like the agent on travis has an issue rather than the test?

**Comment by slide** [comment]
Close and reopen for another build try.

**Comment by filmor** [comment]
@slide Really sorry for the mess, could you please resubmit the PR? I accidentally merged it when trying to update it to the current master and my browser got stuck ...

**Comment by slide** [comment]
Sure, not a problem. I assume you will revert the commit?

**Comment by filmor** [comment]
I immediately force-pushed the previous state.

**Pull request merged**
