### PR TITLE
Add custom converters

### PR DESCRIPTION
**Pull request by ZrifBSofiane**
### What does this implement/fix? Explain your changes.
This change allow to create and register custom converter (Codecs).
You can convert Python to .Net and .Net to Python.

Usefull if want to have a numpy array directly from .net for example.

### Does this close any currently open issues?

...

### Any other comments?

...

### Checklist

Check all those that are applicable and complete.

-   [x ] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [x ] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [x ] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/pythonnet/pythonnet?pullRequest=1177) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/pythonnet/pythonnet?pullRequest=1177) before we can accept your contribution.<br/><br/>:x: ZrifBSofiane [sign now](https://cla.dotnetfoundation.org/pythonnet/pythonnet?pullRequest=1177)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/pythonnet/pythonnet?pullRequest=1177) it.</sub>

**Comment by lostmsu** [comment]
A very similar feature was already added in 2.5.0: [Codecs](https://github.com/pythonnet/pythonnet/wiki/Codecs:-customizing-object-marshalling-between-.NET-and-Python)

**Comment by ZrifBSofiane** [comment]
They are set as obsolete, will they be removed ? Can we still use them ?

**Comment by filmor** [comment]
It's the other way round. There is no "unstable attribute" in C#, so we abuse the `ObsoleteAttribute`. They are usable. Is there something missing?

**Comment by lostmsu** [comment]
@ZrifBSofiane they are set to obsolete to indicate, that API is potentially in flux. They will likely not have `Obsolete` attribute in 3.0. .NET just does not have a similar `Experimental` attribute.

**Comment by lostmsu** [comment]
@ZrifBSofiane they are actually experimental, and the `Obsolete` will likely just go in 3.0

**Comment by ZrifBSofiane** [comment]
Ok cool. I will use it then. 

Thank you !

**Pull request closed without merging**
