### PR TITLE
Clean-up Tests

### PR DESCRIPTION
**Pull request by vmuriart**
### What does this implement/fix? Explain your changes.
- Remove dependency on `six`
- Fixes broken tests
- Improves Py2/Py3 testing
- Adds unused modules
- Comments broken modules
- Simplifies tests
- Renames tests
- Many pep8 clean-ups

### Does this close any currently open issues?
No

### Any other comments?
Recommend `squash&merge`.  Left as separate commits for anyone that wants to see the logic for some of the changes.

### Checklist

Check all those that are applicable and complete.

-   [x] Make sure to include one or more tests for your change
-   [x] If an enhancement PR, please create docs and at best an example
-   [x] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [N/A ] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by denfromufa** [comment]
any reasoning for removing dependency on six?

**Comment by vmuriart** [comment]
It wasn't necessary. This way the compatibility module is *frozen* for our tests. ie, won't be surprised if `six` introduces a bug in the future.

**Comment by denfromufa** [comment]
@vmuriart i'm big minus one on removing dependency from six, it is third most dependent package on pypi:

http://kgullikson88.github.io/blog/pypi-analysis.html

it is very unlikely that we are smarter than all these folks using six.

i do not want to maintain our own subset of six, unless there is unresolved issue with six affecting us.

**Comment by vmuriart** [comment]
@denfromufa. We [barely used](https://github.com/pythonnet/pythonnet/blob/cf5035c176ce2b8009f94e601ff0dad99feba552/src/tests/test_generic.py#L11-L14) `six`. Mostly we used `six` to check if we were in PY2 or PY3 and then created our own compatibility variable. Since we don't support py25, py32, we don't need `six.u(...)`. The only remaining usage for `six` were two calls to `indexbytes`.

I [refactored all the checks](https://github.com/pythonnet/pythonnet/pull/329/commits/d35a4725e3b06b01e36fd8c1c4df8c315a3fdd22) into the [compat module](http://lucumr.pocoo.org/2013/5/21/porting-to-python-3-redux/). I dont think its worth to keep six only for `indexbytes`.

**Comment by denfromufa** [comment]
@vmuriart I agree, good catch on six. let's get rid of it. give me some time to review this PR after 2.2 release.

**Comment by vmuriart** [comment]
@denfromufa no worries. I want to merge #301 first, and then work on this one. There's going to be a merge conflict after 2.2.0, but i should be able to fix it quickly.

**Comment by vmuriart** [comment]
@filmor did you get a chance to check this out?

**Comment by filmor** [comment]
Yep, seems fine on my machine ;)

**Comment by filmor** [comment]
You probably should have squashed this before merging :)

**Comment by vmuriart** [comment]
I was debating it, there are some benefits to squashing (compress history), but at the same time there are some losses when going back threw commit history and trying to understand why a file was added/removed.

Personally I clean-up the history before submitting the pull request. That way it has my logical units of change, without having my 10,000 commits saying "FIXUP! typo" 👍

**Pull request closed without merging**
