### PR TITLE
Catching exceptions from iterator MoveNext() (related to #475) 

### PR DESCRIPTION
**Pull request by rickardraysearch**
### What does this implement/fix? Explain your changes.

Catches exceptions in iterator MoveNext() and throws them in python instead of crashing.

### Does this close any currently open issues?

Issue #475 
### Any other comments?

...

### Checklist

Check all those that are applicable and complete.

-   [x] Make sure to include one or more tests for your change
-   [x] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [x] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by rickardraysearch** [comment]
For future reference, the only place where a general "catch (Exception E)" is done without throwing away the outermost exception is in TypeMethod.Invoke.

**Comment by denfromufa** [comment]
@rickardraysearch can you clarify about that TypeMethod.Invoke? Is this an issue or just a note?

**Comment by rickardraysearch** [comment]
@denfromufa , I only wanted to note that the usage is not completely consistent across all invocations of Exceptions.SetError(). When we revisit how to do the SetErrors, I want to remember this without having to find it out again.

**Comment by denfromufa** [comment]
@filmor @vmuriart please review!

**Comment by vmuriart** [comment]
What happens if you call `next()` after the exception is thrown? Might be worth adding a test for it to make sure it has expected behavior.

Other than adding that test, ok to merge

**Comment by denfromufa** [comment]
> What happens if you call next() after the exception is thrown? Might be worth adding a test for it to make sure it has expected behavior.
> 
> Other than adding that test, ok to merge

@vmuriart did you mean calling this part twice?

```
with pytest.raises(OverflowException) as cm:
    next(val)
```

**Comment by denfromufa** [comment]
@vmuriart or did you mean to verify this behavior?

https://stackoverflow.com/a/11366139/2230844

**Comment by vmuriart** [comment]
both :).

**Comment by denfromufa** [comment]
@rickardraysearch can you please address the suggestions from @vmuriart and then we can merge this!

**Comment by ArvidJB** [comment]
We just ran into the same issue that this pull request is going to fix. Is there any particular reason this was never merged? If there is further work to be done we would be happy to help.

**Comment by denfromufa** [comment]
@ArvidJB i just updated this branch with latest master and CI tests look good. You can add 2 additional unit tests suggested by @vmuriart but personally I approved this PR. If one more core developers approves, then we can merge this. @filmor had a question and that probably can be addressed in another PR.

**Comment by ArvidJB** [comment]
@denfromufa / @vmuriart I think this boils down to adding the following lines
```
    # after exception is thrown iterator is no longer valid
    with pytest.raises(StopIteration):
        next(val)
```
to `test_iteration_innerexception`. Should I create a new pull request for that or would you be willing to add those lines to @rickardraysearch 's request?
I tested @rickardraysearch 's changes and they work as intended.

**Comment by denfromufa** [comment]
@ArvidJB please fork @rickardraysearch branch and make a new pull request with your changes. If you PR looks good, then we can close this PR.

**Comment by ArvidJB** [comment]
@denfromufa I just submitted #693 with the enhanced testing

**Comment by filmor** [comment]
Merged as #693.

**Pull request closed without merging**
