### PR TITLE
Added inline comment about dangers of multidomain usage

### PR DESCRIPTION
**Pull request by jakrivan**
As requested here: https://github.com/pythonnet/pythonnet/pull/538#issuecomment-364630052

### What does this implement/fix? Explain your changes.

Just a commnet

### Does this close any currently open issues?

No. But comment was requested

### Checklist

Check all those that are applicable and complete.

-   [ ] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [x] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [x] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by denfromufa** [comment]
@jakrivan please update the changelog and add yourself to authors.

**Comment by jakrivan** [comment]
@denfromufa Thanks. Done

**Comment by filmor** [comment]
Argh, didn't notice that this was against the "featured" branch. I'll cherry pick it on master...

**Comment by denfromufa** [comment]
@filmor would you like to revert this PR from featured branch managed by @dmitriyse ?

**Comment by filmor** [comment]
Not particularly, no. This is just an additional comment and the featured branch (as essentially a fork) shouldn't exist in the first place.

**Pull request merged**
