### PR TITLE
Added side-by-side VS 2017 build with NetStandard 1.5 support.

### PR DESCRIPTION
**Pull request by dmitriyse**
### What does this implement/fix? Explain your changes.
Added new files that allows to build PythonNet targeting NetStarndard 1.5
Current build scripts are not affected.

All code modification should be loss-less for current build configurations.

New VS 2017 build files are capable to build net40 and NetStandard 1.5 assemblies.

This change is a first CoreCLR compilable version. Probably it is not functional yet.
The work is in progress.

Also CoreCLR assembly/package now have 3.0.0-alpha version. Probably it's ok, if PythonNet with CoreCLR support is scheduled to 3.0.0
...

### Does this close any currently open issues?
Not closes yet but relates to https://github.com/pythonnet/pythonnet/issues/96
...

### Any other comments?

We can join this branch into the master even now, and continue to develop with the additional target (NetStandard 1.5).
But it is reasonable to do it after the point where both Windows and Linux configurations will be tested.
...

### Checklist

Check all those that are applicable and complete.

-   [ ] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [x] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [x] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by dmitriyse** [comment]
I will inject ReflectionBridge right into PythonNet, to save single-Dll deployments.

**Comment by vmuriart** [comment]
Alot of your changes are also changing the encoding of the files. 
I'll review this in more detail, but I think there's still room to improve compatibility to avoid having multiple `#if NETSTANDARD 1.5` sections.

**Comment by denfromufa** [comment]
@vmuriart did you have a chance to review this .net core integration?

**Comment by vmuriart** [comment]
Very much against it in the current form.
+ Adds too many build directives, making the code complicated. We just removed a bunch of them for PY2/PY3, don't want to readd them now for this
+ No new CI added for `.net core`. If something is added and breaks we won't know.

A better path would be to either refactor some more or completely move to it.

**Comment by denfromufa** [comment]
We can't move completely to .NET Core, it doesn't support DllExport and
demo apps will break. So .NET Framework should still be tested.

**Comment by denfromufa** [comment]
@dmitriyse can we close this pull request, or is this still part of other pull requests for .NET Core support?

**Comment by dmitriyse** [comment]
Yes, we can definitely close this PR. It's outdated. We will not support .NetStandard lower than 2.0.

**Pull request closed without merging**
