### PR TITLE
Don't throw exceptions during dynamic access

### PR DESCRIPTION
**Pull request by filmor**
The return value is meant to carry the failure information. This should make code using `dynamic` quite a bit quicker.

### What does this implement/fix? Explain your changes.

Does not through exceptions anymore in dynamic member access and instead communicates failure via the return value.

### Does this close any currently open issues?

#874

### CODE REVIEW

**Comment by filmor** [comment]
I think this fixes a possible memory leak as well, in the case where we fail to set an attribute.

**Comment by filmor** [comment]
Yes, I think we should detect `AttributeError`s and otherwise pass on the underlying exception. It does indeed break the API slightly, but it should have always worked this way.

**Comment by lostmsu** [comment]
@filmor can you think of a scenario, where this change is necessary?
TBH, documentation on .NET docs is not clear about the expected behavior in case member is present, but attempting to access it throws some exception.

**Comment by filmor** [comment]
The scenario is the linked issue where a lot of useless exceptions are being thrown, maybe during probing the dynamic objects.

**Comment by lostmsu** [comment]
@filmor just came up with 2 ways to do it properly:
1. (obvious) Check using `HasAttr` first
2. Only in case of exception, check `HasAttr`. If it does not, return `false`, otherwise rethrow.

**Comment by filmor** [comment]
Ah, sorry, I didn't see your message. Yes, option 2 sounds quite reasonable, although I still think it's a bit too defensive. Nevertheless, I'll change it like this and leave a comment.

**Comment by lostmsu** [comment]
@filmor I'd argue if you can't set a member in Python, the exception you get must be meaningful in nearly 100% cases?

**Comment by lostmsu** [comment]
I dunno. I liked the TryGetMember part, as it does reduce the debug output.

**Pull request closed without merging**
