### PR TITLE
Refactor directives

### PR DESCRIPTION
**Pull request by vmuriart**
Refactors all those pesky #if to simplify process of supporting newer python versions.

Theres a section in runtime I left untouched as it has many embbded directives.

### CODE REVIEW

**Comment by denfromufa** [comment]
@vmuriart so now we need to use both python3 and python3x flags?

**Comment by filmor** [comment]
Yes. And .NET doesn't really have a way around that, AFAICT.

**Comment by denfromufa** [comment]
@vmuriart is it also possible to do this at the top of the file:
```
#if (PYTHON32 || PYTHON33 || PYTHON34 || PYTHON35)
#define PYTHON3
#endif
```

**Comment by vmuriart** [comment]
It would be needed across every file that needs that directive.  http://stackoverflow.com/questions/30350738/where-to-specify-preprocessor-directives-in-visual-studio

The project file is updated to have PYTHON2 set on it though, you would just need to update that on your build config to PYTHON3

**Pull request merged**
