### PR TITLE
Prepare Release of 2.5.0

### PR DESCRIPTION
**Pull request by filmor**
### What does this implement/fix? Explain your changes.

...

### Does this close any currently open issues?

...

### Any other comments?

...

### Checklist

Check all those that are applicable and complete.

-   [ ] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [ ] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [ ] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by lostmsu** [comment]
@filmor just realized codecs are not mentioned in the changelog: https://github.com/pythonnet/pythonnet/wiki/Codecs:-customizing-object-marshalling-between-.NET-and-Python

**Comment by lostmsu** [comment]
@filmor maybe also mention, that the new version is nearly twice as fast, as 2.3.0 was (on interop): https://ci.appveyor.com/project/pythonnet/pythonnet/builds/32947325/job/87g1s6lyi9vqn95v#L2757 😎

**Comment by filmor** [comment]
I'll add both, will first try to get the RC to pypi :)

**Comment by lostmsu** [comment]
@filmor did you have a chance?

**Pull request merged**
