### PR TITLE
Uni-50101-Fixing_the_domain_reload_crash_on_second_init

### PR DESCRIPTION
**Pull request by lassond**
* Now calling PythonEngine.Shutdown on app domain unload

### CODE REVIEW

**Comment by lassond** [comment]
Sorry, wanted to open against our new fork

**Comment by filmor** [comment]
Is there any reason not to merge it here as well?

**Comment by lassond** [comment]
No reason except that we would like to test more scenarios. But feel free
to merge and we’ll follow up with anything else we end up fixing.

Cheers!
David

**Comment by denfromufa** [comment]
@lassond a unit test or a repoducible crash report would be handy too

**Comment by lassond** [comment]
Yes, I will make sure to write a unit test. Hopefully I can manage to
figure out how to reproduce from scratch (the crash happens in the context
of an application I do not have the code for);
- execute Python code with Python .NET
- app domain reload of the assembly
- execute Python code with Pytjon .NET

—> crash on second init when the runtime imports the « exception » module.
The import hook « saved » original funtion ptr must be garbage at this
point.

Anyway, I will reopen the pull request or create a new one when everything
is done.

Thanks!

**Comment by lassond** [comment]
Hi Benedikt and Denis,

I am working on a pull request to get my fix to this crash in the public
repo. I created an issue:
https://github.com/pythonnet/pythonnet/issues/714

I am now following the steps for contributing:
https://github.com/pythonnet/pythonnet/blob/master/CONTRIBUTING.md

About the branch name in my fork, is this ok:
fix/develop/shutdown_on_domain_unload

or should it be
fix/lassond/shutdown_on_domain_unload


Can you clarify these points for me please:
* Make sure your commit messages are in the proper format
What is the proper format?

* Make sure you have added the necessary tests for your changes.
* Run all the tests to assure nothing else was accidentally broken.
Can you give me steps on how to run and add tests please? I created a
standalone app that reproduces the crash. I will gladly try and translate
it to a proper test.

Thanks and keep up the good work, Python .NET is an impressive project!
David

**Pull request closed without merging**
