### PR TITLE
Increase ob's ref count in tp_repr to avoid accidental free

### PR DESCRIPTION
**Pull request by DanBarzilian**
### What does this implement/fix? Explain your changes.

Fix incorrect dereferencing wrapper object in tp_repr function, which causes the program to crash.

### Does this close any currently open issues?

...

### Any other comments?

...

### Checklist

Check all those that are applicable and complete.

-   [ ] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [x ] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [x ] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/pythonnet/pythonnet?pullRequest=1160) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/pythonnet/pythonnet?pullRequest=1160) before we can accept your contribution.<br/><br/>:x: DanBarzilian [sign now](https://cla.dotnetfoundation.org/pythonnet/pythonnet?pullRequest=1160)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/pythonnet/pythonnet?pullRequest=1160) it.</sub>

**Comment by filmor** [comment]
@lostmsu We should probably do a point-release for this, agree?

**Comment by lostmsu** [comment]
@filmor I have another one too in the recent params array change.

**Comment by lostmsu** [comment]
BTW, @DanBarzilian , a personal thank you 10x! This finding and the fix for it just saved me after 3 workdays of chasing a semi-random segfault in tests. I don't know how much time I would have wasted trying to find this.

Funnily, while searching for (apparently) this issue, I stumbled and fixed another less impacting one: https://github.com/losttech/pythonnet/commit/74e7d626f2e18d1f239c712bb7bcedb1ebc61288

**Comment by lostmsu** [comment]
@filmor @koubaa we should mandate using `*Reference` types in new PRs. This bug would have been prevented by proper typing.

**Comment by koubaa** [comment]
@lostmsu now it explains why the CI has been unreliable recently.  Big whoops for missing this and yes more evidence to use Reference types.  Good catch @DanBarzilian

**Pull request merged**
