### PR TITLE
Slack integration for Travis and Appveyor

### PR DESCRIPTION
**Pull request by filmor**

### CODE REVIEW

**Comment by vmuriart** [comment]
How does it work for forks? Do we get notifications for the fork builds too?

**Comment by filmor** [comment]
I don't think so, we'd need to set them up individually. Is that needed, though?

**Comment by vmuriart** [comment]
It's not. I actually wanted to make sure we **don't** get them. I build alot on CI, so wouldn't want to spam everyone.

**Comment by filmor** [comment]
I guess we'll need to try this out :)

**Comment by vmuriart** [comment]
Nothings posted on Slack. Maybe after its merged to `master`? The `push` builds should already be using the new CI configs though.

**Comment by vmuriart** [comment]
Did you generate a new Key? may want to squash the first 2 commits to kinda-hide the private key. 
Even if we squash-merge, the commits of the `pr` won't get erased, thus squashing them before kinda hides them.

**Comment by filmor** [comment]
It's posted in the #ci channel and works already for Travis, still waiting on the results for Appveyor. And there's no need to hide anything, after the first commit I generated a new token (invalidating the previous one) and put it into the file in encrypted form.

**Comment by vmuriart** [comment]
Awesome, wasnt sure if a new token was generated. cool. And sweet, I hadn't noticed the `#ci` channel. I see it now.

**Comment by filmor** [comment]
Theoretically, we don't need to change anything on the repo itself for this to work with Codecov, so this is read for merge.

**Comment by vmuriart** [comment]
Just pushed a build to my fork after adding ontop of the current `master`. Travis finished a few minutes and so far hasn't uploaded anything (good).

**Pull request merged**
