### PR TITLE
Fix implementing a generic interface with a Python class

### PR DESCRIPTION
**Pull request by filmor**
### What does this implement/fix? Explain your changes.

#1982

### Does this close any currently open issues?

...

### Any other comments?

...

### Checklist

Check all those that are applicable and complete.

-   [x] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [ ] Ensure you have signed the [.NET Foundation CLA](https://cla.dotnetfoundation.org/pythonnet/pythonnet)
-   [ ] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [ ] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by filmor** [comment]
@lostmsu Do you have a hint what to do here? The issue is that `MarshalByRefsBack` calls `MethodBase.GetMethodFromHandle(methodHandle)` without also passing a `RuntimeTypeHandle`. Where would we get this type handle from?

**Comment by lostmsu** [comment]
@filmor I seem to be able to push to your repository o-O which I discovered trying to answer your question.

**Comment by filmor** [comment]
You can because you are a maintainer and I always enable that flag on PRs ;). Thanks for the fix!

**Comment by lostmsu** [comment]
missed a place in IR generator, should be working now

**Pull request merged**
