### PR TITLE
Support ARM architectures again

### PR DESCRIPTION
**Pull request by filmor**
### What does this implement/fix? Explain your changes.

Adds ARM versions to the native page hack used to survive app-domain reloading.

### Does this close any currently open issues?

#873

### CODE REVIEW

**Comment by filmor** [comment]
@benoithudson, could you have a look?
@bimajatiwijaya, could you check whether this branch works for you?

**Comment by filmor** [comment]
The only thing I have is an old Raspberry Pi and a few phones, I just used godbolt to get the binaries. That's why I'd like people that had problems to test this branch ;)

**Comment by amos402** [comment]
Ummm, I think it seems that it would better if we create a dynamic library and use P/Invoke to get a function address rather than making some hard codes like these?

**Comment by filmor** [comment]
That would complicate the build process quite a lot though. I'd really like to get to a single arch independent assembly in the future that can just be compiled using dotnet cli without any additional params.

**Comment by amos402** [comment]
But at first, you always need to build a sample binary and disassembly to get codes depend the system.
If you worry about the build process, why not just upload that prebuilt binary to repository, so that users would not need any compile.
What if we need to compatible systems like these:

How complicated would `typemanager.cs` be......

**Comment by filmor** [comment]
The trick is that it's straight binary, so you only need one of these per cpu arch, not per os (no ELF vs PE distinction, no libc linking etc). Be my guest in providing a reasonable alternative.

**Comment by amos402** [comment]
Oh, it is. I almost neglect it.

**Comment by benoithudson** [comment]
> That would complicate the build process quite a lot though. I'd really like to get to a single arch independent assembly in the future that can just be compiled using dotnet cli without any additional params.

Me too, which is why my patch that introduced this code was discovering the platform at runtime rather than with ifdefs.

If there's some rainy days I'll see about converting more of the code. Eliminating the MONO_LINUX and MONO_OSX defines would be nice; UCS as well.

**Comment by amos402** [comment]
By the way, the implementation for `Runtime.InitializePlatformData` just have some limitations.
Not `platform.py` would import `subprocess`, but not all release binaries have it, I encounter it before and use ifdef skiped, any good suggestion?

**Comment by benoithudson** [comment]
Probably inline the two functions. IIRC one of the calls has a CPython component, the other I didn't track down.

We're getting pretty far off the original topic, I wonder if comments on this PR are the best way to gather our thoughts?

**Pull request merged**
