### PR TITLE
Fixed errors breaking .NET Remoting on method invoke (#276)

### PR DESCRIPTION
**Pull request by denfromufa**
### What does this implement/fix? Explain your changes.

https://github.com/pythonnet/pythonnet/issues/276

### Checklist

Check all those that are applicable and complete.

-   [ ] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [ ] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [ ] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by denfromufa** [comment]
@callumnoble @jcarole this PR for .NET Remoting cannot be merged, because more general solution that would work on .NET Core is necessary. .NET Remoting is deprecated and its API is not available in .NET Core and .NET Standard.

**Comment by jcarole** [comment]
@denfromufa Just to confirm, does this mean that Pythonnet 2.0.0 will be the last version that supports .NET Remoting?

**Comment by callumnoble** [comment]
For my application which needs this I'm deploying a wheel I built with 2.3 + this patch. Is working well.

I see the fails from the CI build. Would you support an `#if / #endif` conditional for building .NET with version that supports remoting. By definition this check does not need to run on .NET Core since the remoting the library uses wont have been able to run on it!

The same define as used here could work?
https://github.com/pythonnet/pythonnet/blob/df2aa64f192d986bf3cd086e53ae7e8b72fa534e/src/runtime/nativecall.cs#L26

**Comment by jcarole** [comment]
@denfromufa @callumnoble Exactly. Since .NET Remoting isn't supported by .NET Core (yet, and probably ever), a conditional compilation solution seems ideal.

**Comment by callumnoble** [comment]
@denfromufa opened new pr for this #637

**Pull request closed without merging**
