### PR TITLE
Addresses issue #261 with providing more detail information missing d…

### PR DESCRIPTION
**Pull request by fdanny**
This addresses issue #261 to provide more information when there is a missing assembly dependency.  The logic basically does the following
1.  After importing module check if an ImportError exception occured
2. If it does load the assembly dependencies and try to load each one
3. if I can't load that assembly I add to the list
4. At the end I display the list of missing assemblies.

### CODE REVIEW

**Comment by denfromufa** [comment]
@fdanny can you please add some tests? i.e. you can look at test_import.py file.

**Comment by fdanny** [comment]
@denfromufa Yup. I can do that. The way I tested it I created a dll that had a missing dependency. I made assure my ImportError Exception contained the specific missing dependency. Is this something that you were thinking?

**Comment by denfromufa** [comment]
Yes, that's right!

**Comment by fdanny** [comment]
@denfromufa Is there a location in the solution you want me to put this in TestDependencyAssembly? 

Also why did my test failed on the Travis CI but passed AppVeyor? It has the following error
 clr.AddReference(path_to_dll)
System.IO.FileNotFoundException: Unable to find assembly

**Comment by denfromufa** [comment]
You can just add a new project to solution. Otherwise just compile at
runtime - have a look at clrmagic.


That dll loading issue is pretty weird, please share the source code and
how you compiled it.


Here is repeatable issue using Mono C# REPL when using reflection, but not
when adding reference (LoadAssembly):


```

Mono C# Shell, type "help;" for help


Enter statements below.

csharp>
LoadAssembly("/home/dta/Documents/clrmagic/TestDependencyAssembly.dll")

csharp> using System.Reflection;

csharp> Assembly

Assembly AssemblyAlgorithmIdAttribute AssemblyCompanyAttribute
AssemblyConfigurationAttribute AssemblyContentType
AssemblyCopyrightAttribute AssemblyCultureAttribute
AssemblyDefaultAliasAttribute AssemblyDelaySignAttribute
AssemblyDescriptionAttribute AssemblyFileVersionAttribute
AssemblyFlagsAttribute AssemblyInformationalVersionAttribute
AssemblyKeyFileAttribute AssemblyKeyNameAttribute AssemblyLoadEventArgs
AssemblyLoadEventHandler AssemblyMetadataAttribute AssemblyName
AssemblyNameFlags AssemblyNameProxy AssemblyProductAttribute
AssemblySignatureKeyAttribute AssemblyTitleAttribute
AssemblyTrademarkAttribute AssemblyVersionAttribute

csharp> Assembly testdll =
Assembly.Load("/home/dta/Documents/clrmagic/TestDependencyAssembly.dll")

System.IO.FileNotFoundException: Could not load file or assembly
'/home/dta/Documents/clrmagic/TestDependencyAssembly.dll' or one of its
dependencies

File name: '/home/dta/Documents/clrmagic/TestDependencyAssembly.dll'

  at System.AppDomain.Load (System.String assemblyString,
System.Security.Policy.Evidence assemblySecurity, Boolean refonly)
<0x7f976292e650 + 0x000a2> in <filename unknown>:0

  at System.AppDomain.Load (System.String assemblyString) <0x7f976292e610 +
0x00015> in <filename unknown>:0

  at (wrapper remoting-invoke-with-check) System.AppDomain:Load (string)

  at System.Reflection.Assembly.Load (System.String assemblyString)
<0x7f97629a1980 + 0x0001b> in <filename unknown>:0

  at <InteractiveExpressionClass>.Host (System.Object& $retval) <0x41b71120
+ 0x0001a> in <filename unknown>:0

  at Mono.CSharp.Evaluator.Evaluate (System.String input, System.Object&
result, System.Boolean& result_set) <0x41ae4d30 + 0x000dd> in <filename
unknown>:0

  at Mono.CSharpShell.Evaluate (System.String input) <0x41ae4c30 + 0x00053>
in <filename unknown>:0

csharp> Assembly testdll =
Assembly.Load("/home/dta/Documents/clrmagic/TestDependencyAssembly")

System.IO.FileNotFoundException: Could not load file or assembly
'/home/dta/Documents/clrmagic/TestDependencyAssembly' or one of its
dependencies

File name: '/home/dta/Documents/clrmagic/TestDependencyAssembly'

  at System.AppDomain.Load (System.String assemblyString,
System.Security.Policy.Evidence assemblySecurity, Boolean refonly)
<0x7f976292e650 + 0x000a2> in <filename unknown>:0

  at System.AppDomain.Load (System.String assemblyString) <0x7f976292e610 +
0x00015> in <filename unknown>:0

  at (wrapper remoting-invoke-with-check) System.AppDomain:Load (string)

  at System.Reflection.Assembly.Load (System.String assemblyString)
<0x7f97629a1980 + 0x0001b> in <filename unknown>:0

  at <InteractiveExpressionClass>.Host (System.Object& $retval) <0x41b71690
+ 0x0001a> in <filename unknown>:0

  at Mono.CSharp.Evaluator.Evaluate (System.String input, System.Object&
result, System.Boolean& result_set) <0x41ae4d30 + 0x000dd> in <filename
unknown>:0

  at Mono.CSharpShell.Evaluate (System.String input) <0x41ae4c30 + 0x00053>
in <filename unknown>:0

csharp>

```

**Comment by denfromufa** [comment]
You can just add a new project to solution. Otherwise just compile at
runtime - have a look at clrmagic.


That dll loading issue is pretty weird, please share the source code and
how you compiled it.


Here is repeatable issue using Mono C# REPL when using reflection, but not
when adding reference (LoadAssembly):


```

Mono C# Shell, type "help;" for help


Enter statements below.

csharp>
LoadAssembly("/home/dta/Documents/clrmagic/TestDependencyAssembly.dll")

csharp> using System.Reflection;

csharp> Assembly

Assembly AssemblyAlgorithmIdAttribute AssemblyCompanyAttribute
AssemblyConfigurationAttribute AssemblyContentType
AssemblyCopyrightAttribute AssemblyCultureAttribute
AssemblyDefaultAliasAttribute AssemblyDelaySignAttribute
AssemblyDescriptionAttribute AssemblyFileVersionAttribute
AssemblyFlagsAttribute AssemblyInformationalVersionAttribute
AssemblyKeyFileAttribute AssemblyKeyNameAttribute AssemblyLoadEventArgs
AssemblyLoadEventHandler AssemblyMetadataAttribute AssemblyName
AssemblyNameFlags AssemblyNameProxy AssemblyProductAttribute
AssemblySignatureKeyAttribute AssemblyTitleAttribute
AssemblyTrademarkAttribute AssemblyVersionAttribute

csharp> Assembly testdll =
Assembly.Load("/home/dta/Documents/clrmagic/TestDependencyAssembly.dll")

System.IO.FileNotFoundException: Could not load file or assembly
'/home/dta/Documents/clrmagic/TestDependencyAssembly.dll' or one of its
dependencies

File name: '/home/dta/Documents/clrmagic/TestDependencyAssembly.dll'

  at System.AppDomain.Load (System.String assemblyString,
System.Security.Policy.Evidence assemblySecurity, Boolean refonly)
<0x7f976292e650 + 0x000a2> in <filename unknown>:0

  at System.AppDomain.Load (System.String assemblyString) <0x7f976292e610 +
0x00015> in <filename unknown>:0

  at (wrapper remoting-invoke-with-check) System.AppDomain:Load (string)

  at System.Reflection.Assembly.Load (System.String assemblyString)
<0x7f97629a1980 + 0x0001b> in <filename unknown>:0

  at <InteractiveExpressionClass>.Host (System.Object& $retval) <0x41b71120
+ 0x0001a> in <filename unknown>:0

  at Mono.CSharp.Evaluator.Evaluate (System.String input, System.Object&
result, System.Boolean& result_set) <0x41ae4d30 + 0x000dd> in <filename
unknown>:0

  at Mono.CSharpShell.Evaluate (System.String input) <0x41ae4c30 + 0x00053>
in <filename unknown>:0

csharp> Assembly testdll =
Assembly.Load("/home/dta/Documents/clrmagic/TestDependencyAssembly")

System.IO.FileNotFoundException: Could not load file or assembly
'/home/dta/Documents/clrmagic/TestDependencyAssembly' or one of its
dependencies

File name: '/home/dta/Documents/clrmagic/TestDependencyAssembly'

  at System.AppDomain.Load (System.String assemblyString,
System.Security.Policy.Evidence assemblySecurity, Boolean refonly)
<0x7f976292e650 + 0x000a2> in <filename unknown>:0

  at System.AppDomain.Load (System.String assemblyString) <0x7f976292e610 +
0x00015> in <filename unknown>:0

  at (wrapper remoting-invoke-with-check) System.AppDomain:Load (string)

  at System.Reflection.Assembly.Load (System.String assemblyString)
<0x7f97629a1980 + 0x0001b> in <filename unknown>:0

  at <InteractiveExpressionClass>.Host (System.Object& $retval) <0x41b71690
+ 0x0001a> in <filename unknown>:0

  at Mono.CSharp.Evaluator.Evaluate (System.String input, System.Object&
result, System.Boolean& result_set) <0x41ae4d30 + 0x000dd> in <filename
unknown>:0

  at Mono.CSharpShell.Evaluate (System.String input) <0x41ae4c30 + 0x00053>
in <filename unknown>:0

csharp>

```

**Comment by fdanny** [comment]
@denfromufa I ran into an issue trying to resolve this. My method will only work if the namespace imported is the same as the assembly name.  I have now way of mapping a namespace to an assembly. 

It looks like when `clr.AddReference` called an `AssemblyLoadEventHandle`r is initiated when an assembly is loaded and eventually goes into the `AssemblyManager::ScanAssembly`. It looks like this method parses out the namespaces and loads it into `ConcurrentDictionary`. 

The issue in ScanAssembly is when 
 `types = assembly.GetTypes();
`

This doesn't work since it doesn't have all the dependencies so we don't get the namespace mapping. 

I'm thinking the following maybe

1.  Raise an exception `clr.AddReference` if not all dependencies are present
2.  On a failure on `assembly.GetTypes()` Read the assembly in Stream and parse the out the information sort of like Mono Cecil. 

What do you think???

**Comment by denfromufa** [comment]
@fdanny maybe it is ok without namespace in the error message? but i'm surprised that it is hard to track it down.

**Comment by vmuriart** [comment]
@denfromufa @fdanny is there any help needed for this `pull request` ?

**Comment by denfromufa** [comment]
@fdanny needs help tracking down the namespace name in the Exception traceback

**Comment by filmor** [comment]
The alternative PR #1076 was merged a while ago.

**Pull request closed without merging**
