### PR TITLE
[WIP] WPF DynamicGrid python and XAML layout files

### PR DESCRIPTION
**Pull request by denfromufa**

### CODE REVIEW

**Comment by filmor** [comment]
Is this finished? Are you planning to finish it?

**Comment by denfromufa** [comment]
@filmor this is finished, but @tonyroberts wanted me to add data binding:

https://github.com/pythonnet/pythonnet/pull/185#issuecomment-227966173

**Comment by filmor** [comment]
Can't you add data-binding later on in another PR? I'd like to have the queue clear of those long-lingering items :)

**Comment by denfromufa** [comment]
Sure, data binding and MVVM for another PR! So merging? @filmor  @vmuriart

**Pull request merged**
