### PR TITLE
Support ByRef arguments in event handlers

### PR DESCRIPTION
**Pull request by tminka**
### What does this implement/fix? Explain your changes.

When an event handler has a ByRef argument, extra logic is needed in DelegateManager.GetDispatcher or else the program will access invalid memory and crash.

### Does this close any currently open issues?

#1355 

### Any other comments?

...

### Checklist

Check all those that are applicable and complete.

-   [X] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [X] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [X] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by lostmsu** [comment]
This still does not allow python to change the value under the memory location passed by reference?

Ideally, a special Python `ByRef` type should be constructed to hold the value until function exits, then the caller should check if Python updated the value in the `ByRef` instance, and update the value pointed by reference accordingly.

**Comment by tminka** [comment]
Perhaps, but your scenario is not the one in #1355 .  This PR at least prevents crashes.

**Comment by lostmsu** [comment]
Since you can't override Python assignment operator, this fix is fundamentally incompatible with the proper solution with `ByRef`, so will have to be replaced by 3.0.0.

Even if we don't implement updating the value right now, for compatibility the value has to be wrapped into some Python object instance.

E.g. in the linked issue the handler code should be
```python
def handleEventData(data):
    print("=== event invoked. data: {} ===".format(data.Value)) # NOTE .Value
```

**Comment by tminka** [comment]
When Python calls a .NET method with ref arguments, it returns a tuple of out/ref parameters, and if there's a return value it is the first in the tuple.  See [methodbinder.cs](https://github.com/pythonnet/pythonnet/blob/92932fd2a615e7ddcf16c4e4441a4840050b6bc9/src/runtime/methodbinder.cs#L962) and [stackoverflow](https://stackoverflow.com/questions/2857287/writing-iron-python-method-with-ref-or-out-parameter). Therefore the "proper solution" is for `handleEventData` to return a tuple of out/ref parameter values.  No special `ByRef` type is needed.

**Comment by lostmsu** [comment]
Good point. Still for forward compatibility we must at least check Python returns a tuple of the correct size, or better yet actually implement the marshaling of data back to the event.

**Review by lostmsu — APPROVED** [review]

**Comment by noambonnieclear** [comment]
So is this supposed to be released with 2.5.2?

**Pull request merged**
