### PR TITLE
Python to CLR string marshaling LRU cache.

### PR DESCRIPTION
**Pull request by dmitriyse**
### What does this implement/fix? Explain your changes.

Adds string marshaling LRU cache (10k entries per marshaling type).
This greatly speedups mixed clr/py code. + Saves big amount of memory on large structures translation.

### Does this close any currently open issues?

...

### Any other comments?

This code is well tested in the high-load project. Memory usage was dramatically decreased after this improvement.

### Checklist

Check all those that are applicable and complete.

-   [ ] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [ ] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [ ] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by vmuriart** [comment]
Can you rebase this PR? looks like it was started out of a different PR that was already merged in.

**Comment by dmitriyse** [comment]
This PR depends on one non merged PR https://github.com/pythonnet/pythonnet/pull/534

Also I rebased all PR that depends on merged PRs #518 and #519

**Comment by denfromufa** [comment]
@jakrivan can you add your comments as inline according to the code changes in this PR:

https://github.com/pythonnet/pythonnet/pull/538/files

**Comment by jakrivan** [comment]
@denfromufa - inline comment added: https://github.com/pythonnet/pythonnet/pull/625

However it's just one from many things that would need to be adjusted to support multi-domain usages. So feel free to reject - not to spoil the code with irrelevant comment.

**Comment by filmor** [comment]
Note to self: This PR needs to be adjusted to the changes I made to PR #534, I renamed the `TestsSuite` class.

**Comment by lostmsu** [comment]
As a performance change this needs to be accompanied by a performance test, that sets up a baseline.

E.g. first, a test must be merged, that sets the baseline performance goal without this change, then this PR should update the goal with the improved value.

**Comment by filmor** [comment]
This is also probably unmergable in its current form, I have just kept it open for reference.

**Pull request closed without merging**
