### PR TITLE
Fix geninterop.py to support c_ast.FuncDecl (Python 3.8 tp_print is a function pointer)

### PR DESCRIPTION
**Pull request by Jeff17Robbins**
### What does this implement/fix? Explain your changes.

Added conditional support to run `geninterop.py` on Windows 10.  Added support for function pointers (`c_ast.FuncDecl`) to fix `interop38.cs` for Python3.8.

### Does this close any currently open issues?

close issue #995 

### Any other comments?

...

### CODE REVIEW

**Comment by filmor** [comment]
Great, thanks :)

Could you also regenerate `interop38.cs` with this?

**Comment by Jeff17Robbins** [comment]
@filmor I'm not experienced at git, so I hope I did this correctly.  Happy to learn, so if I made mistakes, please let me know!

**Comment by filmor** [comment]
The only non-ideal thing is that you changed the line-endings, the rest is fine :)

I'll see whether I can easily fix this and then we'll merge, thank you very much for your contribution. It would be good if you could add yourself to the AUTHORS.md file as well.

**Comment by Jeff17Robbins** [comment]
I saw that line-ending issue when Github showed me the diff.  I definitely felt bad about it, but as a long-time Windows/Microsoft developer (first started on AppleSoft Basic and Microsoft's "The AppleSoft Compiler (TASC)) around 1982, at least I have an excuse.  

If you want me to try changing some Visual Code setting and doing it again, happy to do so!

**Comment by filmor** [comment]
Merged manually, the whitespace modifications are apparently too much for Github to recognise this. Thanks a lot for the analysis and fix.

**Pull request closed without merging**
