### PR TITLE
WPF DynamicGrid python and XAML layout files

### PR DESCRIPTION
**Pull request by denfromufa**
based on @tonyroberts example from mailing list:

https://mail.python.org/pipermail/pythondotnet/2015-June/001653.html

This version allows to design XAML in Visual Studio using ironpython project and run it in both ironpython and pythonnet later.

### CODE REVIEW

**Comment by tonyroberts** [comment]
I think it would be better to get rid of the IronPython references as it's a pythonnet demo. Having it work with both might be nice, but I think it could be seen as a bit confusing.

**Comment by denfromufa** [comment]
The reason why ironpython is added - to make sure that Visual Studio XAML
designer can be used to design and check for errors interactively and with
intellisense using PTVS.

@tonyroberts, PTVS is officially supported by Python team at Microsoft.

So is there any alternative to not reference ironpython, e.g. to design
XAML without project? apparently this was possible in older versions of VS:

http://stackoverflow.com/questions/28375682/edit-standalone-xaml-with-visual-studio-intellisense

**Comment by tonyroberts** [comment]
XAML is just a text file, so you can edit it using whatever text editor you like - VS is not required. I've used http://www.kaxaml.com/ in the past.

**Comment by denfromufa** [comment]
@tonyroberts I only agree partially with you. XAML is not just text file - it is rendered as GUI and for newcomers this visual part of designing in VS is essential. In VS 2015 you can even debug XAML! People may have success with kaxaml, but it has not been developed for 5 years - no issues, no pull requests! if there is any other alternative to VS WPF XAML designer, please let me know?

https://github.com/thinkpixellab/kaxaml

**Comment by tonyroberts** [comment]
vim? notepad? My point is that these demos should be what you minimally need to demonstrate a feature. If you want to write blog posts or whatever about how to debug xaml using visual studio then that would be great, but cluttering code with reference to ironpython when it's not strictly necessary (and with no explanation of why it could be desirable) isn't the best way to highlight features.

**Comment by denfromufa** [comment]
@tonyroberts apparently it is possible to switch the interpreter in PTVS, so no issues with removing ironpython refs.

**Comment by denfromufa** [comment]
@tonyroberts I removed ironpython refs long ago

BTW, here is another WPF demo:

https://github.com/hhspiny/WPFPy

**Comment by tonyroberts** [comment]
I think a WPF demo should include some data binding.

**Comment by denfromufa** [comment]
According to contributing guidelines this pull has to be open for 2 weeks
for addressing comments, before closing.

**Comment by tonyroberts** [comment]
It was closed as a side effect of the develop branch being deleted. Please feel free to re-open against the master branch.

**Comment by tonyroberts** [comment]
Which reminds me... I need to update the contributing file to say that PRs against master are now preferred!

**Comment by denfromufa** [comment]
Thanks for clarifying!

**Pull request closed without merging**
