### PR TITLE
LookupType returns the first type found

### PR DESCRIPTION
**Pull request by Cronan**
### What does this implement/fix? Explain your changes.
In .Net Core 2.0, there are public and private versions of the same types in different assemblies. For example, there is a private version of System.Environment in mscorlib.dll, and a public version in System.Runtime.Extensions.dll. The existing code returns the first matching type found, even if it's private, and even if there are other matching types in other assemblies. 

The new version of this function returns the first public type, or the first type found.
### Does this close any currently open issues?

This closes some parts of #613 

### Checklist

Check all those that are applicable and complete.

-   [x] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [x] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [x] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by denfromufa** [comment]
@Cronan i can't find any reference to this issue, i understand that writing test is hard, but please provide a reference comment or exception traceback at least.

**Comment by Cronan** [comment]
@denfromufa The issue in #613 `from System import Environment` is caused by this bug - it occurs in Linux using .Net Core 2.0, when using the code from #612.

I'll add a test that exercises the import above, but it will only fail when #612 is merged into master (and if the above code isn't added)

**Comment by Cronan** [comment]
@denfromufa Added a test, merged from #621, and squashed.

**Comment by denfromufa** [comment]
@Cronan let's wait for CI to finish

**Comment by Cronan** [comment]
@denfromufa Sorry (sadface)

**Comment by dmitriyse** [comment]
I also have related PR https://github.com/pythonnet/pythonnet/pull/528/commits

**Comment by dmitriyse** [comment]
That exists since summer 2017.

**Comment by denfromufa** [comment]
@dmitriyse this PR addresses one stand-alone issue, I'm in favor of merging your PR, if it totally covers this case and if you cherry pick the unit test from this PR to your PR.

**Comment by Cronan** [comment]
@dmitriyse @denfromufa It seems I spent a lot of time yesterday debugging and fixing an issue that has already been fixed, but was left unreviewed and unmerged. :-(

What is hard about this project right now is the large number of issues, combined with a large number of unreviewed and unmerged PRs, which make it increasingly difficult for new people to work on the project. Obviously #610 was meant to address this, but I think we also need to work through the PRs, and either merge, fix, or close them. Maybe we could take them one at a time, and focus in on them?

**Comment by denfromufa** [comment]
@Cronan with new rules in issue #610 we should be able to faster merge existing PRs at least between me and @dmitriyse. I have more time this year than in second half of 2017. Soon we may add more reviewers from active people with few accepted PRs.

**Comment by denfromufa** [comment]
@Cronan also checkout the featured branch:

https://github.com/pythonnet/pythonnet/tree/featured

**Comment by Cronan** [comment]
Thanks @denfromufa

**Comment by Cronan** [comment]
@denfromufa  I'm going to close this, I'll add the test (with a few others) by itself as a separate PR to extend code coverage.
@dmitriyse I'm not sure #528 actually address the issue of importing System.Environment in dotnetcoreapp2.0 on Linux, but I may be wrong.

**Pull request closed without merging**
