### PR TITLE
Add very simple example editor

### PR DESCRIPTION
**Pull request by gpetrou**
### What does this implement/fix? Explain your changes.

I am doing my first steps in Python .NET and I created a small editor project in order to test the library. Looking for information on how to redirect output to C# and interrupt execution, I saw that other people had the same questions. So, I thought of making this small contribution to get other people started with this library instead of looking for the same things as I did.

### Checklist

Check all those that are applicable and complete.

-   [ ] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [x] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [x] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/pythonnet/pythonnet?pullRequest=1333) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/pythonnet/pythonnet?pullRequest=1333) before we can accept your contribution.<br/><br/>:x: gpetrou [sign now](https://cla.dotnetfoundation.org/pythonnet/pythonnet?pullRequest=1333)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/pythonnet/pythonnet?pullRequest=1333) it.</sub>

**Comment by filmor** [comment]
Hi,

First, thank you for your contribution. To me, these really look like two separate PRs, one for the `Interrupt` function and one for the `Editor` example.

Regarding the `Interrupt`:
1. This requires a test
2. Strictly, the thread-id attribute is `unsigned` only for Python >= 3.7 and we still support 3.6
3. Also, since the original type is `long`, the "correct" type is `(U)IntPtr` on everything but Windows
4. (Not quite sure how far we have to go there compatibility-wise, the current implementation could be fine for the usual thread IDs)
5. Maybe we should just expose the API function directly (i.e. `RaiseInPythonThread` on `Exception` objects or so) and make `Interrupt` use that

Regarding the `Editor`:
1. Should be in its own PR
2. Should not be in `src/`
I didn't read the actual code yet, but a self-contained example like this is definitely a useful addition.

**Comment by lostmsu** [comment]
I'd say example of this size should have its own repo.

**Comment by gpetrou** [comment]
@filmor any thoughts on this now that the Interrupt PR was separated?

**Comment by lostmsu** [comment]
> I'd say example of this size should have its own repo.

**Review by PACE100 — APPROVED** [review]
First Time Coding

**Pull request closed without merging**
