### PR TITLE
Official python 3.7 support

### PR DESCRIPTION
**Pull request by denfromufa**
### What does this implement/fix? Explain your changes.

add py37 support

### Does this close any currently open issues?

https://github.com/pythonnet/pythonnet/issues/609

### Any other comments?

TODO:

- [x] waiting for appveyor ci support
- [x] resolve pycparser error
- [x] update project files Python.Runtime.csproj and Python.Runtime.15.csproj
- [x] travis ci settings: https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-402045581
- [x] update classifiers in setup.py
- [x] mono/nuget/msbuild issue

### Checklist

Check all those that are applicable and complete.

-   [x] Make sure to include one or more tests for your change
-   [x] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by filmor** [comment]
What's left to do here?

**Comment by denfromufa** [comment]
also official python 3.7 support in travis ci now requires xenial, not trusty. Hence this may create some unexpected issues with Mono:

https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-402045581

**Comment by stonebig** [comment]
so which of appveyor/pr or appveyor/branch is the one to take ?

**Comment by denfromufa** [comment]
@stonebig both branches should be identical.

**Comment by denfromufa** [comment]
Upgrading from python 3.7-dev to 3.7 proper on travis ci is throwing a new error:

```
/opt/python/3.7.0/include/python3.7m/pythread.h:122:5: error: "Require native
      threads. See https://bugs.python.org/issue31370"
#   error "Require native threads. See https://bugs.python.org/issue31370"
```

https://travis-ci.org/pythonnet/pythonnet/jobs/415741697#L1999


Plus something in the Mono toolchain broke over the last 6 days, which is causing msbuild issues:

https://github.com/Microsoft/msbuild/issues/3604

**Comment by stonebig** [comment]
+1 on removing Python-3.4 support.

**Comment by Gravityzwell** [comment]
_@stonebig py34 is supported until March 2019:_

Personally I find 3.7 support much more compelling, if it's a one or the other type of thing. Also, anyone can still use the older version pythonnet for 3.4. There are many such cases where older libs QT etc. are not compatible in different ways, which is one of the reasons for virtual envs.

**Comment by filmor** [comment]
I don't know where this py34 discussion is coming from, it's no either/or wrt py37 support.

**Comment by stonebig** [comment]
@filmor I suggested droping  py34 because was the one failing at the time https://ci.appveyor.com/project/pythonnet/pythonnet/build/master-1271

**Comment by denfromufa** [comment]
Py34 is failing just because I temporarily enabled super detailed build
logging and CI is going crazy - read the commit message.

**Comment by denfromufa** [comment]
Ok, I'm really puzzled why travis ci is failing with mono/nuget/msbuild/xbuild toolchain. I just tried to reproduce the issue in Virtualbox with no luck:

https://gist.github.com/denfromufa/23557331aba2ad548eba2fbff84f2307

**Comment by denfromufa** [comment]
https://stackoverflow.com/questions/51988395/build-failures-with-mono-5-14-0-177-msbuild-15-0-nuget-4-7-1-on-travis-ci-but

**Comment by denfromufa** [comment]
Ok, I'm going to try previous versions of nuget and msbuild, like suggested in stackoverflow:

nuget 4.6, msbuild 15
nuget 4.7, msbuild 14
nuget 4.6, msbuild 14

And maybe then previous version of Mono (hopefully not!)

**Comment by denfromufa** [comment]
@filmor justing waiting for appveyor builds 🕐

**Comment by filmor** [comment]
We're working on it, 6 merges in the last week, 7 PRs marked as 2.4.0 still to go.

**Pull request merged**
